### ISSUE TITLE
Kopirovani gridu

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#10]
Pridat funkci na zkopirovani gridu
- asi pridat moznost "novy jako" a pak se mi nabidnou gridy co existujou. Ja vyberu a vse se mi predvyplni nastavenim toho puvodniho. Ja upravim dam novy nazev a ulozim.
- nema prioritu, jen abych nezapomnel.

**Comment by jzelenka** [comment]
hotovo.
vyberes existujici grid a pak das Kopirovat. Grid se zkopiruje do noveho, neulozeneho zatim. Pak upravis nazev a das ulozit.
