### ISSUE TITLE
aktivni/neaktivni a platne/neplatne

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#100]
Product, Party, Vehicle maji vlastnost active = true/false
 - doplnil jsem filtrovani do vyberu, tj. neaktivni se nenabizeji
 - pokud uz napr. vehicle ma party, ktera se pozdeji stane neaktivni, tak to funguje spravne - je videt, ale kdyz ji odvyberu tak uz ji zpatky nevyberu.

**Na Party a Produktu byla chyba ze se pres UI vytvarely neaktivni. Az do ted se to nijak neprojevovalo. Ted je to ale videt a nejdou vybrat**

**Na produkci je jeden neaktivni produkt a 508 neaktivnich party. Pokud jsi ty pres SQL schvalne neoznacoval nejakou party jako neaktivni, tak je vsechny updatuj na aktivni.**

Pro uplnost, ciselniky maji platnost valid_from - valid_to.  Tam uz filtrovani je a navic to umoznuje vztahnout platnost k nejakemu datumu do minulosti, pokud by bylo potreba (pr. customer zalozeny do nekdy by mel mit jine ciselnikove polozky nez novy customer). Tohle zatim samozrejme nikde nepouzivame, tj. platnost se overuje podle aktualniho datumu.

**Comment by milant007** [comment]
Updatnuto, vsichni jsou ted actvive true
