### ISSUE TITLE
Save document - definování názvu souboru

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#101]
Bylo by možný si nastavit pod jakým názvem se bude dokument stahovat do PDF? Teď je to univerzálně Invoice PDF_čísloFA.pdf
Teď přistál požadavek z SK, že jim vadí že dobropis se stahuje jako Invoice. Tak si říkam, že někdo další bude chtít taky definovat vlastní název souboru, tak zda by to třebas v document types nešlo vydefinovat? Případně rovnou podle jazyka/země...

**Comment by jzelenka** [comment]
nastavuje se to na documentTemplate, nove policko documentNameExpression.
Kdyz je prazdne, funguje to jako dosud.

Kdyz tam napr. das:
`invoiceType.label + '_' + invoiceNumber`

dostanes Invoice_201620003.pdf nebo Credit note_201620003.pdf

Kdyz nechces mezeru v nazvu souboru, muzes dat:

`invoiceType.label.replace(' ', '_') + '_' + invoiceNumber`

pak dostanes Credit_note_201620003.pdf

**Comment by milant007** [comment]
Je mozny ze mam zase problem mezi klavesnici a zidli? Dal jsem to na produkci(refresh, clear cache) k Volvu SK, vyplnil jsem:
`invoiceType.label.replace(' ', '_') + '_' + invoiceNumber` a porad to exportuje Credit note jako Invoice...

**Comment by jzelenka** [comment]
nazev se ulozi do dco_document pri vytvorteni dokumentu, tedy pri issue.

**Comment by milant007** [comment]
ok funguje.
