### ISSUE TITLE
Nastavení balíčků - default pro Platnost od

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#102]
Pokud se zadává přímo v definici vozidla balíček dpr_product_vehicle, tak chtějí předvyplnit default datum platnosti od(valid_from) 1. dne následujícího měsíce.
Ono pak by se to možná chtělo zamyslet nad nějakým globálním řešením defaultních hodnot napříč celým ZauZoo...

**Comment by jzelenka** [comment]
Udelal jsem to globalni reseni.
Nastavuje se na Administration / Entities
vyberes Entitu a v ni vyberes Field

A na fieldu pridas jeden nebo vice defaultu. Urovne defaultu jsou USER, TENANT, TENANT_GROUP, GLOBAL.
Priorita dle tohoto poradi.

Hodnota defaultu je konstanta nebo javascript expression pro dynamicke hodnoty. Expression zacina znakem `#`  (neni soucasti expression, odtrhne se)

Napr.  

      #moment().add(1, 'months').startOf('month').format("YYYY-MM-DD")

je ten prvni den nasledujiciho mesice.

Serverove expression zatim nepodporujeme.

Je to pridane na vetsinu veci, ktere vidi zakaznik (ne treba na eventTemplate apod.).

S vyjimkou faktury, kde se inicializuje slozite na serveru rada policek z Customera. Pokud by se potreba objevila, muzeme to pridat i na fakturu, ale museli bychom rozmyslet co ma prioritu.

Vyplni se pouze policka, ktera nejsou vyplnena natvrdo v kodu (napriklad ted mam na customerovi natvrdo Default send type = POST, takze toto policko ted nejde defaultama ovlivnit).

Na testu jsem nastavil:

Pro Volvo SK na Party defaultni hodnoty pro Currency, Language, Nationality a Tax Domicile.
 - tyto jsou nastaveny jako konstanta
 - protoze se to nastavuje na Party, vyplnuji se i pro Kontaktni Osoby a SalesRep. Coz asi nevadi. Kdyby to vadilo, muselo by se nastavit pomoci js expression s podminkou na partyType. Kdyz tak ukazu.

A pro cele Volvo jsem nastavil ten pocatek platnosti balicku jak ukazano vyse. (ProductVehicle  validFrom)

**Comment by jzelenka** [comment]
a musi se dat clear cache

**Comment by milant007** [comment]
Toto dnes poslali Rumuni, ty to mas natvrdo...
Hello,
Can you change the default mailing selection for new customers from „Post” to E-mail” ?.

**Comment by jzelenka** [comment]
odstranil jsem z tvrdeho defaultu, muzes si to ted nastavit defaultama. Viz rumuni na testu.
Clear cache.
