### ISSUE TITLE
Ukladani kontaktu - chyba

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#104]
Chci ulozit v tenantovi MultiData u Volvo Hungaria kontaktni invoicing email _szamla@volvo.com_ pro fakturaci a vyhniva to s touto chybou(+ chyby na Slacku). Napada me ze by mohl delat problemy tenant group v kombinace s logovanim zmen?
Client Error
Error: Request failed with status code 500 at e.exports (https://www.zauzoo.com/module-6bd68b6a.js:15:6508) at e.exports (https://www.zauzoo.com/module-6bd68b6a.js:22:30847) at XMLHttpRequest.p.(anonymous function) (https://www.zauzoo.com/module-6bd68b6a.js:15:5605)
×
Server error 500
NullPointerException:

**Comment by jzelenka** [comment]
Lze to zreprodukovat na testu? (Sedim na porade)

**Comment by milant007** [comment]
Na testu to funguje, vecer jsem daval novou verzi do produkce, Pak Clear Cache i Refresh. A stejne to v produkci nejde a na testu jo.
Nehori to, je to pro me potreby az budu fakturovat madary, kteri jeste nezaplatili ani cent!

**Comment by jzelenka** [comment]
Udelej deploy app i fe a zkus to znovu

**Comment by milant007** [comment]
pomohlo. ale deploy jsem delal i vcera odpoledne po 17. hodine, tak jsem myslel ze jsi uz mezitim nic nedelal. Kazdopadne vyreseno.
