### ISSUE TITLE
vyvoj sablon tisku faktur

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#11]
Pro vyrobu PDF tisku faktur budeme pouzivat apache xsl-fop.
Cely retezec je:
databaze -> java objekt -> XML -> PDF

Ukolem toho bugu napsat XSLT sablonu, ktera provede konverzi XML -> PDF.

Pouzivam defaultni  XSLT, to je XSLT 1, Pokud byste chteli XSLT 2 (vice funkci apod), tak dejte vedet, pouzili bychom Saxon.

Ve finale budou sablony ulozeny v databazi v `tco_document_template` , ale nyni pro vyvoj sablony, ji budete mit normale v souboru a transformaci budete spoustet JUNIT testem v `InvoiceTests.printInvoice()`
Z toho je vsechno videt, zadava se tam cislo faktury, cesty k souborum.....

Jak rozchodit java IDE a pustit ten test vam ukaze Martin.

 Pri spusteni testu se vypisuje na konzoli XML, ktere je vstupem transformace. Pokud by v nem neco chybelo (a bylo to v DB) ozvete se.

- zda se, ze faktury (Volvo, Renault) se lisi pouze logem a to je urcene strediskem - potom by mohla byt sablona pouze jedna. Jak vlozit logo, je popsano ve vzorove sablone, kterou posilam mailem, nejde prilozit.

- vyber sablony je nyni mozny podle strediska a jazyku.

### Lokalizace:
1. lokalizace statickych testu    
  a) pro kazdy jazyk sablona
  b) jedna sablona, v sablone budou klice formou `xsl:param` a vlastni preklady klicu v databazi 

  nyni predpokladam a) , pokud chcete b) dejte vedet musim to dovyvinout

2. lokalizace ciselniku - jiz funguje (pouze u ciselniku, ktere jsou nadefinovane jako lokalizovatelne), napriklad Country - preklady jsou v tabulce `tco_locale_table`
 
 Az pustite test uvidite, ze se pro _en a _cs PDF tisk preklada zeme v adrese (v XML se v zavislosti na jazyce meni element `label` elementu `country` na adrese)

**Comment by milant007** [comment]
Layout bude delat Jindra, vi co je potreba, pripadne Martin vypomuze.

k te lokalizaci statickych textu bych uvital moznost b) Nicmene ted koukam ze cesky volvo za celou dobu nevystavovalo jedinou FA v cizim jazyce, vse pouze v cs. Takze ma otazka zni, kdyz se ted udela varianta a) jak tezky by to pak bylo predelat na b) ?

**Comment by jzelenka** [comment]
pujde to, vetsina prace je u vas:
- Vy nahradite vsechny staticky texty v sablone klicema a a naplnite tabulku hodnotami pro jednotlive jazyky.
- ja doprogramuju aby tty klice sly v sablona pouzit - celkem malo prace

**Comment by milant007** [comment]
nehori to, az budes mit cas a chut tak to priprav

**Comment by jzelenka** [comment]
Jindro, udelej si obcas git pull - neco jsem tam menil.

**Comment by jzelenka** [comment]
pridal jsem to. udelej si pull.

verze XSLT se kontroluje v InvoiceTests: `documentTemplate.setUseSaxonForXslt(true);`

Ve vlastni sablone lze overit treba takto:

					<fo:block>
						<xsl:text> Version: </xsl:text>
						<xsl:value-of select="system-property('xsl:version')" />
						<xsl:text> Vendor: </xsl:text>
						<xsl:value-of select="system-property('xsl:vendor')" />
						<br />					
					</fo:block>

**Comment by krivohlavek** [comment]
Ještě bych do XML potřeboval dostat:
1) IČ a DIČ pro odběratele + dodavatele
2) Textovou poznámku pro celou fakturu

Chtěl jsem kouknout do webového rozhraní a najít si nějakou větší fakturu, ale nedaří se mi přihlásit (HTTP Status 404 - /api/public/tenant - The requested resource is not available.)

**Comment by jzelenka** [comment]
Aplikaci na zauzoo.com jsem rozchodil, bylo to zpusobene tim, ze posloucha na stejnem portu (8080) jako tomcat6 (apache-tomcat-6.0.36) , ten uz nema zadne webapps, tak jsem ho vypnul a disabloval v chkconfig.
Jeste tam byla dalsi chyba zpusobena tim, ze spring boot nerozbaluje archiv, bezi to z jaru, a pristup na soubory v jaru (na classpath) je mozny jen pres getResourceAsStream(), File object pro soubory v jaru nefunguje, ruzne resource base nastaveni nefunguji...

Prakticky to znamena, mozne problemy pri odkazovani externich entit (obrazku, fontu..) ze sablony. Budeme je resit az nastanou - v me vzorove sablone je ten watermark, ten funguje, az budes resit obrazky (logo), tak se ozvi.  Ono to taky jeste jinak funguje pri spusteni testu z IDE (protoze soubory jsou rozbalene, neni jar) a pri standardnim behu aplikace (vse z jar).



> 1) IČ a DIČ pro odběratele + dodavatele

IC a DIC jsem pridal.

> 2) Textovou poznámku pro celou fakturu

Na fakture jsou 2 poznamky: `comment`, `internalComment`  , obe v XML jsou - samozrejme jen pokud jsou vyplnene. Z podstaty veci se pro tisk jedna asi o `comment`.

Dival jsem se a nejsou vyplnene nikde:

      select * from din_invoice where comment is not null
      0 rows
      select * from din_invoice where internal_comment is not null
      0 rows

Nevim jestli je to chyba migrace nebo je Volvo nepouziva.

**Comment by milant007** [comment]
poznamky jsem tam updatnul, skripty pro import upravil, udelejte git pull

**Comment by jzelenka** [comment]
Vzor sablony a souvisejici soubory jsem dal do repository `zauzoo/tool`, udelej si `git clone`.
(InvoiceTests je odkazuje, takze si v nem budes muset zeditovat cesty).

Klidne dej svoji sablonu taky do zauzoo/tool, finalne sice bude v db, ale ma dost dlouhy vyvoj, tak at je radsi verzovana...

Ve vzorove sablone `invoice_vzor.xsl` jsou vyresene vsechny potrebne veci:

1. **lokalizace statickych souboru**
 - pomoci xml souboru pro jednotlive jazyky, pr. `invoice_properties_cs.xml` , tyto soubory musi byt vlozeny jako `resources` pro sablonu (nyni v InvoiceTests, finalne totez, ale pres GUI do DB)
 - ve vzorove sablone viz klic `total.amount`

2. **obrazky**
 - neni treba includovat v base64, normalne odkazte relativne viz `logo_1.gif`, opet je zadefinovane jako resource.
 - jak je videt v sablone, tak ta 1 v `logo_1.gif` je ID profitCentra, pomoci cehoz se rozlisuje logo Volvo x Renault

3. **formatovani datumu, ruzne pro ruzne jazyky**
 - pomoci XSLT2 funkce `format-date`, pripadne `format-datetime`, `format-time` a formatovaciho stringu, ktery je dostupny v sablone jako parametr. Viz `invoiceDate`
 - je trosku otazka jak formatovat datum v anglictine, protoze anglie ma dd/MM/yyyy a amerika MM/dd/yyyy.  Dal jsem dd/MM/yyyy, ale pripadne to muzeme zmenit.

4. **formatovani cisel, ruzne pro ruzne jazyky**
 - pomoci XSLT funkce `format-number`, deklarace `xsl:decimal-format` pro vsechny jazyky a  formatovaciho stringu, ktery je prekladan v properties xml souborech. Viz `totalPriceLcy`

**Comment by krivohlavek** [comment]
Ještě bych potřeboval přihodit do xml následující pole:
	- IČ DPH
	- osoba vystavující fakturu
	- email na osobu vystavující fakturu
	- webové adresa společnosti
	- email společnosti
	- telefon společnosti
	- fax společnosti
	- záznam společnosti v obchodním rejstříku

**Comment by jzelenka** [comment]
- IČ DPH 
pridano

- osoba vystavující fakturu
- email na osobu vystavující fakturu

Milane - chybi data - musi to byt Party (asi s roli Kontaktni Osoba treba) navazana na fakturu pres `din_invoice_role` s `invoice_role_type_id` = 1 (Issued By).
Email pak bude normalne v kontaktech te osoby - contactTypeId = 1 (Email).
Kdyby to nefungovalo az budou data, ozvi se (nejsou data = neotestoval jsem).



- webové adresa společnosti
- email společnosti
- telefon společnosti
- fax společnosti

Tohle vsechno jsou kontakty party (kontakty drive nebyly, pridal jsem je). Nove jsem pridal contactType:
5, 'fax'
6, 'web address'

musite si vypnit data na party Volva..

	- záznam společnosti v obchodním rejstříku
pridano pole, ale musite si vyplnit data...

**Comment by jzelenka** [comment]
@milant007

**Comment by milant007** [comment]
Vsechno doplneno/upraveno, Jindro muzes vyzkouset.

**Comment by krivohlavek** [comment]
V xml to stale nevidim, git pull jsem daval.

**Comment by jzelenka** [comment]
co nevidis?

**Comment by krivohlavek** [comment]
Omlouvám se a beru zpět. Někde to asi viselo v cache, protože teď už to tam vidím :-)

**Comment by krivohlavek** [comment]
Ještě poprosím o icoDph pro <billedTo>, teď je jen u <billedFrom>.

**Comment by jzelenka** [comment]
u ceho? 
mel by tam byt, kontrolovals ze je v db?

**Comment by krivohlavek** [comment]
Jo v db to nebylo, očekával jsem prázdný element v xml a když jsem ho neviděl, tak jsem psal :-( Po doplnění db to jede.

**Comment by jzelenka** [comment]
no null hodnoty v db prazdny elementy nedelaji, da se to mozna zmenit, ale uz tak to XML je veliky...

**Comment by milant007** [comment]
Dotaz, Jindra ma dovolenou a my potrebujeme(s Michalem) doplnit na Fakturu IČ DPH dodavatele. Zákazníkovo tam máme, ale nevíme kde vzít to dodavatele a zda to vůbec plníš a pokud ano, tak kde to vzít?

**Comment by jzelenka** [comment]
Dodavatel je v elementu `billedFrom`

Zakaznik (element `billedTo`) a dodavatel (element `billedFrom`) se serializuji (= vyplivnou xml) uplne stejne. Takze pokud ma party dodavatele vyplnene icoDph, melo by v XMLku byt.

Btw. mail s touto poznamkou me prisel pred 5 minutama a maily o tech dnesnich 2 novych bugach vubec... asi to maji dneska rozesrane.... obcas maji nejake problemy.

**Comment by jzelenka** [comment]
@milant007 

Zmena v adresach:
nove budou mit parties na fakture (billedTo a billedFrom) vzdy 2 adresy:
jednu trvalou:

       <addressType>PERMANENT</addressType>
 a jednu korespondencni:

       <addressType>CORRESPONDENT</addressType>


Takze v sablone nebudes muset mit zadnou logiku, proste u Sidla das trvalou adresu a na miste postovni das korespondencni.

V kodu to je zde, kdyby ses chtel podivat:
[PartyJaxbInvoiceAdapter](https://github.com/zauzoo/app/blob/86b4e5fa05fe7b4671dd5527b54a88539b935d85/src/main/java/com/zauzoo/party/binding/jaxb/PartyJaxbInvoiceAdapter.java)


Je proto nutne aby adresy byly spravne vyplnene, kdyby treba customer mel adresu typu OTHER misto PERMANENT, tak drive to asi chodilo, ale ted uz ne - v XML nebude mit zadnou adresu.

Pridal jsem kontrolu ze party s roli customer musi mit 1 PERMANENT adresu.

**Comment by jzelenka** [comment]
Dodelal jsem ukladani sablon v DB + GUI (Administrace / Document Types)
V GUI je rovnez mozne testovat - spoustet sablonu proti datum. Melo by to pouzivat  pro vyvoj sablony misto InvoiceTests.

Je to popsane v https://github.com/zauzoo/app/wiki/Dokumenty
prosim prectete to a kdyz tak zavolejte. Jinak se tam pracuje s language (locale) a profitCenter.

Tedka k jednotlivym dokumentum / exportum:

Madarske XML:
- vytvoril jsem documentType InvoicesHuTaxExport + sablonu
- pro add-hoc zavolani pro N faktur:  
 - v madarskem tenantovi vyberte jednu nebo vice faktur (musite je zaskrtnout) a potom bude dostupna volba Bulk Actins:

![image](https://cloud.githubusercontent.com/assets/1957955/14421425/d10304c8-ffd1-11e5-9093-a2574a75cc3b.png)


Slovensky TXT export:
 - podobne jako madarske XML, ale nevlozil jsem documentType - udelejte si sami - a ani to nedal do GUI - predpokladam ze to jednou bude automaticky job, takze to do GUI nepatri. Proto to zatim musite volat pres InvoiceTests - udelal jsem nove metody, ktere ctou sablonu z DB (a taky se tam jinak pracuje s LANG a profitCenter, viz wiki).  Ty stare jsem prejmenoval na ...Old.

PDF faktury
- vytvoril jsem documentType Invoice + sablonu
- bude se vytvaret pri vystaveni faktury, proto zatim musite volat pres InvoiceTests, opet jsem vytvoril novou metodu, starou prejmenoval na ...Old
- vyvoj sablony byste meli delat v GUI.


Taky me zajima jestli se v GUI sablony vyviji lepe nez pres InvoiceTests - jedine v cem me napada ze by to mohlo byt horsi je, ze ted musite pripravit to XML pres export do formatu XML Object, zatimco drive jste v InvoiceTests jen zadali ID faktury - ale zase jste nevideli jednoduse to XML, coz potrebujete pro vyvoj sablony..... 


Zaviram.
