### ISSUE TITLE
Zakládání obchodních partnerů funkci

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#14]
#### Zde je popis jak probiha zalozeni partnera v MD, nejakou podobnou logiku by to chtelo do ZZ
parametry funkce:
- IČ - podívá se zda náhodou není již v DB založen, pokud ANo tak jen otevře již existující kartu(detail). Jinak vyhledá v ARES a načte potřebné údaje do DB.
- Jméno, příjmení, email - vyplním tři pole pokud vím kontaktní osobu, abych nemusel skákat na záložku Kontaktních osob. V ZZ by to nemuselo být třeba pokud bychom kontaktní osobu č.1 dostali do formuláře? Pokud bychom ji nechali na založce "Kontaktní osoby" tak bych ten parametr při založení nechal
- ADMIN login, ADMIN pwd - pole která slouží pro evidenci hesel přidělených ze Švédska pro administraci partnera ve webovém rozhraní. na to bude třeba nová tabulka pro evidenci login a hesel?
- USER login, USER pwd - pole která slouží pro evidenci hesel přidělených ze Švédska pro přístup uživatele do webového rozhraní. na to bude třeba nová tabulka pro evidenci login a hesel?
- VOLVO LOGIN(checkbox) - pokud zaskrtnuto, generuje(inkrementuje o 1) se automaticky LOGIN VOLVOxxx s fixnim heslem. uz nevim k jakemu ucelu slouzi toto heslo s loginem.
- RENAULT LOGIN(checkbox) - pokud zaskrtnuto, generuje(inkrementuje o 1) se automaticky LOGIN RENAULTxxx s fixnim heslem. uz nevim k jakemu ucelu slouzi toto heslo s loginem.
- Obchodni zastupce1 - nabidka z obchodnich zastupcu v DB
- Obchodni zastupce2 - nabidka z obchodnich zastupcu v DB

po založení/vyhledání se otevře detail toho partnera aby uživatel mohl případně doplnit další informace.

**Comment by jzelenka** [comment]
Ted budu uvazovat jak by to slo udelat minimalisticky - tj. bez specialniho formulare na zakladani:
(je to trosku vic klikani, ale ne o moc a zase je to konzistentni - vsechny entity maji seznam -> detail)

1. uzivatel vybere v menu Party / Customers a zobrazi se mu seznam zakazniku
2. pokud vi, ze zakaznik neexistuje muze dat rovnou v toolbaru "New Customer", pokud nevi, vyhleda v gridu podle ICO a bud otevre existujiciho nebo da "New Customer" kdyz nebude nalezeno....
3. Ve formulari "New Customer", ktery je stejny jako "Edit Customer" (je to proste detail zakaznika), zacne vyplnovat zakaznika a bude mu to delat online kontroly:
  - kdyz vyplni pole Nazev, vypise warning kdyz customer se stejnym nazvem uz existuje
  - kdyz vyplni ICO, ktere uz existuje, vypise chybu, nedovoli ulozit
4. Vedle pole ICO bude ikonka, ktera na zaklade ICO natahna data z ARESu do ostatnich poli

5. Kontaktni osoby a Obchodniho Zastupce - podle me to je podobne s tim rozdilem, ze Kontaktni Osoba se temer vzdy zaklada nova (nemela by v pripade, ze fyzicky je jeden clovek kontaktni osobou ve vice firmach), kdezto Obchodni zastupce se vetsinou vyhleda existujici a jen nekdy zaklada novy?
 - takze bude muset jit na zalozku (rekneme ze Kontaktni osoby bude na detailu zakaznika prvni zalozka, tedy defaultne otevrena), kde bude primo moznost "Vytvor novou", ktera otevre modalni okno s detailem customera - fyzicke osoby bez zalozek, jen zakladni policka. Dale pro moznost nalinkovat existujici tam bude policko kam bude moct zacit psat a bude mu to nabizet existujici osoby. Aby nejak vyuzil kdyz napise jmeno a prijmeni a zjisti ze neexistuje, tak pak po kliknuti na Vytvor novou se predvyplni napsany text treba podle konvence Jmeno mezera Prijmeni,

Co se tyce tech vsech loginu a hesel, tak jedna moznost je ze budou primo na formulari  - pak by to byl specificky formular pro Volvo. Alternativne :speech_balloon:  - ted musim odskocit k datovemu modelu:

Mame nyni 3 velmi podobne 1:N tabulky k Party -  dpa_party_contact, dpa_party_role, dpa_party_feature (neni nepouzivame). Pouzival bych to takto:

dpa_party_contact - sem jen data slouzici ke kontaktu (email, telefon, datova schranka, webova adresa, ...)

dpa_party_role - sem jen ty, kde je to skutecne "role", treba toho Notifikovaneho obchodniho zastupce u balicku. 

dpa_party_feature - pridal bych sem datove pole value1, ... value10 a vyuzil to na ty loginy. Takze by byl jeden featureType - VOLVO_LOGINS - a zakladal by se jeden radek do dpa_party_feature s typem VOLVO_LOGINS, kde by v polich value1 az value8 byly to loginy a hesla - vsechny v jednom radku, protoze spolu trochu souvisi.
Tedy vyznam hodnot v valuesX polich by byl ruzny podle featureType.

Je to takovy kompromis mezi narvat vsechny ty pole na d_party a mit v dpa_party_feature jen jedno pole value a 8 radku....

ted navazu na GUI - alternativne  :speech_balloon: by ty loginy byly na zalozce features, ktera by se editovala modalem, ktery by byl specificky pro kazdy featureType. Vyhoda proti prvni variante, je ze je to obecne - Cely formular zakaznika by byl obecny a pouze by byl naprogramovan maly formular pro featureType VOLVO_LOGINS.

Co ty na to?

**Comment by milant007** [comment]
Zakládání obchodního partnera souhlasím s postupem. 1 vyhledám,  když neexistuje 2. dám nový, 3. zadám ičo a kliknu natáhni data 4. doplním vše ostatní

Co se loginu tyce, muze to tak byt. Akorat k tomu mam to, ze nekteri zakaznici co maji napr nejakou webovou aplikaci pro partnery a neni to dostatecne sofistikovane aby to samo menilo hesla a tak... , tak si v MD login a heslo uchovavaji u kontaktnich osob neb je sami prideluji. A tak nevim zda by to neslo jeste nejak zobecnit? dela to tak napr HEIRU a BB.

**Comment by jzelenka** [comment]
kontaktni osoby mohou mit taky features, tak by se udelal jinej featureType, treba CUSTOMER_WEBAPP_LOGINS, kterej by mel svuj, trochu jinej formular, treba s policky nazevWeboveAplikace, login, heslo, ktery by tam byly 3x, pro az tri aplikace.

Jediny drobny problem je, ze zatim nemame nijak omezene jaky featureType se bude nabizet, kdyz se pridava nova featura, jinymi slovy, na zakaznikovi by pouzili featureType VOLVO_LOGINS a na kontaktni osobe CUSTOMER_WEBAPP_LOGINS.

**Comment by milant007** [comment]
Kdyz nad temi loginy premyslim, tak bych se s tim ted asi nedrbal a udelal to nejjednodussi variantou z duvodu casove tisne. az to budem resit jinde, tak se to zobecni?

**Comment by jzelenka** [comment]
Predelavat neco existujiciho je strasnej opruz - predelavat datove struktury, migrovat data...
Lepsi je to navrhnout co nejvice ve finalni podobe a treba neco nemit hotove hned.

Takze jestli je navrh vyse OK, tak bych to tak udelal.

**Comment by milant007** [comment]
an je to ok, muze byt :-)

**Comment by jzelenka** [comment]
Pres partyFeature jsem udelal:

>ADMIN login, ADMIN pwd - pole která slouží pro evidenci hesel přidělených ze Švédska pro >administraci partnera ve webovém rozhraní. na to bude třeba nová tabulka pro evidenci login a hesel?
>USER login, USER pwd - pole která slouží pro evidenci hesel přidělených ze Švédska pro přístup >uživatele do webového rozhraní. na to bude třeba nová tabulka pro evidenci login a hesel?


Toto

>VOLVO LOGIN(checkbox) - pokud zaskrtnuto, generuje(inkrementuje o 1) se automaticky LOGIN >VOLVOxxx s fixnim heslem. uz nevim k jakemu ucelu slouzi toto heslo s loginem.
>RENAULT LOGIN(checkbox) - pokud zaskrtnuto, generuje(inkrementuje o 1) se automaticky >LOGIN RENAULTxxx s fixnim heslem. uz nevim k jakemu ucelu slouzi toto heslo s loginem.

jsem nepochopil, takze jestli je to potreba, tak to lepe popis do noveho bugu.

ostatni veci asi jsou hotove nebo zastarale.
zaviram.
