### ISSUE TITLE
Funkce na hromadne prirazeni balicku - pouze VOLVO

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#15]
Jedna se o funkci kde nad vybranymi vozidly(v ZZ v gridu) spustim funkci ktera priradi konkretni balicky a s nimi i dalsi data spojena(cena, upozorneni atd.) Funkce se da vyuzit i pro jedine zafiltrovane vozidlo pro prirazeni, je to jednodussi nez auto rozkliknout a zadavat v detailu.

Vstupni parametry:
- platnost od
- Datum upozorneni - viz: https://github.com/zauzoo/app/issues/12
- text upozorneni - viz. https://github.com/zauzoo/app/issues/12 
- cena - vyplnuje se pokud je nestandardni za vybrane balicky, jinak cenu definuji na urovni zakaznika a balicku
- Balicky - v MD je to ted checkbox kde si mohu vybrat i nekolik balicku, ktere se nasledne priradi ke vsem vybranym vozidlum. Zaroven se ke vsem balickum rozkopiruje pripadny zadany text upozorrneni, datum upozorneni, cena

po spusteni funkce udela hromadny insert vybranych balicku k vybranym vozidlum spodminkou ze jiz balicek u auta neexistuje. pote nastavi upozorneni a pripadne ceny.

Na zamysleni je, kam si budes v projektu davat veci ktere jsou pouze pro VOLVO jako je tato.

**Comment by jzelenka** [comment]
Bude se to lisit podle toho jak se to projevuje v UI, v tomto konkretnim pripade, kdy se jedna o tlacitko na toolbaru gridu, budou tyto tlacitka enablovana pro jednotlive tenanty. Tedy neco jako tabulka
cto_gridaction_tenant.

Na implementaci je cas az se bude delat nekdo dalsi nez Volvo.

**Comment by milant007** [comment]
Dotaz k teto funkcionalite, dnes vyvstal pozadavek, kdy potřebují v SK hromadně nastavit balicky u vybranych aut. Dokazes udelat nejaky muster jak vytvaret funkce abych to tady mohl trebas hodit na nekoho z kluku?

**Comment by jzelenka** [comment]
asi ne, ja to udelam, neni to tolik prace. Teda pokud se to udela takto:

- nebude tam upozornovani (to budeme resit zvlast pozdeji).
- bude to uplne stejny formular jaky je tedka na detailu auta. Pri ty prilezitosti bych do nej dodelal moznost pridat cenu (na urovni PRODUCTVEHICLE). Tj. pujde tim pridat jen jeden balicek - ale auta zustanou oznacena, takze pak muzou pokracovat.

**Comment by milant007** [comment]
- datum a text upozorneni ted nejsou dulezity, to muzem vynechat, dulezity ted je priradit hromadne balicek a pripadne jej nacenit.
- ten formular si moc nedovedu predstavit, ale vyberu si v gridu auta a nad temi spustim funkci "Prirad balicek" a zadam jaky balicek a platnost od kdy, pripadne cenu a jeji platnost. funkce ke vsem vybranym autum priradi ten balicek(pokud existuje tak nic) do dpr_product_vehicle a updatne valid_from pokud jej zadaji. Pak pokud zadaji i cenu tak se porovna jestli se lisi od ceny ktera je ted pro to auto nastavena, a to muze byt na vsech trech urovnich v tabulce dpr_price_component. pokud se lisi zjisti zda existuje zaznam v dpr_price_component na urovni PRODUCTVEHICLE kde valid_from se take shoduje(null se shoduji) v tomto pripade udela pouze update ceny, pokud se valid_from lisi, udela update te puvodni kde do valid_to da platnost - 1 a pak insert kde s platnosti valid_from.

Kdyztak radeji zavolej vysvetlim.

**Comment by jzelenka** [comment]
Hotovo.

Spusti se tak, ze vyberes jedno nebo vice vozidel na gridu vozidel nebo subgridu vozidel na Party, potom se enabluje ikona hromadnych operaci (vodorovne carky) na gridu a vyberes Assign Product.

Muzes asignovat vice produktu.

Na produktu jsou datumy validFrom/To, ty se tykaji ProductVehicle, ne ceny. Pokud produkt na vozidle neexistuje, pouziji se. Pokud existuje ignoruji se.
Pak je tam cena a jeji datum validFrom - priceValidFrom.

Pokud je vyplnena cena, tak pokud se lisi od aktualni ceny:
  - pokud existuje cena se stejnym validFrom, pouze se aktualizuje cena
  - pokud je validFrom jine, zalozi se nova cena a pokud je validFrom existujici ceny mensi nez priceValidFrom zkrati se existujici cene validTo, pokud je vetsi, zkrati se nove cene validTo
 - jsou tam ruzne kontroly, ktere vyhodi chybu pro neresitelne situace

**Comment by jzelenka** [comment]
Dale na prirazeni produktu na detailu vehicle, tj. na rozkliknutem radku gridu, lze editovat a pridavat ceny s urovni PRODUCTVEHICLE.

**Comment by jzelenka** [comment]
tam si muzes taky prohlizet co dela ta hromadna funkce...

**Comment by milant007** [comment]
Na prvni pohled to vypada funkcni, super. ale jeste to proklikam dukladneji nez to pustim ven. Jen me napadlo, ze by mozna nebylo od veci mit DB na testovani. ted to sice zkousim nad CZ, kde jsou jen testovaci data, ale porad SK a HU je produkcni a obcas to muze svinit nejak i pres tenanta, viz. prirazovani DPH na produktu, tak abych jim to nerozesral...
