### ISSUE TITLE
Export do účetnictví

### ISSUE THREAD

**Issue by krivohlavek** [zauzoo/app#16]
Kde a jak budou vypadat exporty do účetnictví (SAP,SCALA)?

Funkce:
V pravidelných intervalech (každé ráno) se spustí export (txt soubor) dosud neexportovaných dat (faktur), které se následně pošlou automaticky mailem (různé emaily podle země a SW). Exportovaná data se pak označí jako exportovaná (timestamp exportu, v případě nedoručení aby bylo možné zaslat znovu).

**Comment by jzelenka** [comment]
Ten TXT soubor obsahuje nekolik faktur a kazda faktura zabira nekolik radku?

**Comment by krivohlavek** [comment]
Jo. Neobsahuje to sice konkrétní položky, ale vždy je tam souhrn za tržby, dph ...

**Comment by jzelenka** [comment]
Udelal bych to zase sablonou. 

1. java funkce vytvori XML obsahujici vsechny faktury k exportu.
  Toto XML bude stejne jako mas na tisk, jen bude obsahovat vice faktur:

      <Invoices>
      <Invoice>
       ....
      </Invoice>
 
      <Invoice>
       .....
      </Invoices>

2 . sablona vygeneruje z XML TXT vystup.

Takze vyber faktur k exportu (tj. reseni jestli uz byly exportovane, jak je exportovat znovu v pripade nedoruceni, jak exportovat znovu faktury dodatecne zmenene....) bude 1. krok naprogramovany v jave aplikace sablony bude nasledny krok a odeslani exportu posledni krok.

Ty bys mel ted udelat jen vyvoj te sablony.


Dej vedet jestli ve vyse uvedenem nevidis nejaky problem, pokud ne, pripravim testovaci metodu podobne jako u tisku.

**Comment by krivohlavek** [comment]
Ok, myslim si, ze to tak pujde.

**Comment by jzelenka** [comment]
Tak jsem to commitnul, v te testovaci tride je metoda `exportInvoices()`

taky si pullni repo tool, v nem je pouzity `invoice_export_vzor.xsl` (je v nem treba jak se dela konec radku windows / unix, ja se nastavuje charset textoveho souboru..)

**Comment by jzelenka** [comment]
btw, koukal jsem ze v repo tool neni komitnuta tvoje sablona tisku faktury... dej ji tam prosim.
Kvuli zalohovani a abych se podival :)

**Comment by jzelenka** [comment]
jeste jsem zapomel dodat, ze na root elementu XML jsem udelal soucty vsech peneznich castek faktur, kdyby byly potreba, tak abys je nemusel scitat v XSL sablone.

Soucty policek bez "Lcy"  budou scitat ruzne meny, pokud se fakturuje v ruznych menach....

**Comment by jzelenka** [comment]
@milant007

**Comment by krivohlavek** [comment]
Faktura uz tam komitnuta je. Jen jsem v xml jeste nenasel dodatecne informace o tenantovi (bankovní informace co jsou uvedeny v paticce), v db to myslím je. Zatím to mám v invoice_properties_cs.xml - od supplier.phone do konce.

**Comment by jzelenka** [comment]
Pridal jsem to tam, je to na party - billedFrom.

Kdyz ti bude neco chybet, hned si o to pis...

**Comment by krivohlavek** [comment]
Nějak se rozbil export do účetnictví :-( Zkoušel to i Michal a stejný výsledek.

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 17.436 sec <<< FAILURE! - in com.zauzoo.invoice.service.InvoiceTests
exportInvoices(com.zauzoo.invoice.service.InvoiceTests)  Time elapsed: 2.505 sec  <<< ERROR!
org.springframework.oxm.UncategorizedMappingException: Unknown JAXB exception; nested exception is javax.xml.bind.JAXBException: class com.zauzoo.invoicing.binding.jaxb.InvoiceArray nor any of its super class is known to this context.
```

**Comment by jzelenka** [comment]
opraveno, commitnuto
