### ISSUE TITLE
Chyba pri prihlaseni do tenanta Slovensko

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#17]
Importuji do Party SK a tak jsem se chtel podivat na data a pri prihlaseni do tenanta Slovensko vyskoci: 
Server error 500
org.springframework.transaction.UnexpectedRollbackException: JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is bitronix.tm.internal.BitronixRollbackException: RuntimeException thrown during beforeCompletion cycle caused transaction rollback

pote se to prihlasi, ale do tenanta CZ

**Comment by jzelenka** [comment]
ted jsem to zkousel a chodi to... zkus se odhlasit a udelat to znovu?

**Comment by milant007** [comment]
uz bez chyby, ale data jsou CZ a ne SK

**Comment by jzelenka** [comment]
ok, mrknu to.
Ta prvni chyba je nahodna - muze se jeste vyskytnout, nez ji trvale odstranim (ted jsem nic neudelal).

**Comment by jzelenka** [comment]
oni tam su vseci...  opravim to.

**Comment by milant007** [comment]
do party tenant 3 jsem nasypal madarske zakazniky, ty zas videt nejsou vubec

**Comment by milant007** [comment]
beru zpet, je tam vechno i vcetbne madaru

**Comment by jzelenka** [comment]
oboji opraveno
