### ISSUE TITLE
migrace party

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#2]
Je potreba udelat migraci dat modulu PARTY z volva do zauzoo.
Tyka se to tedy zakazniku a kontaktnich osob.

Predstavuju si to takto:
 * export / import potrebnych tabulek z ORACLE VOLVO do pracovnich tabulek POSTGRES ZAUZOO 1:1 

* skripty (nebo procedury) pro prevod dat z techto pracovnich tabulek do datoveho modelu Party

**Comment by milant007** [comment]
Takze zakladni tabulky:
<ul>
<li>MDKND             tabulka obchodnich partneru. ALE POZOR pokud se (pouze volvo) pole MDKND.IND_POST_KZ = 1 potom, se jedná o postovni adresu a ne o zákazníka. Ta se bude prenaset do adres. 
Pokud zakaznik pouziva vice adres, tak se to pozna tak ze mdknd.knd_id != mdknd.knd_id_ab, v tom pripade je postovni adresa urcena pres mdknd.knd_id_ab s vazbou opet do mdknd.knd_id kde tato adresa by mela mit MDKND.IND_POST_KZ = 1</li>
<li>MDZHD             tabulka kontaktních osob, vazba na zákazníka je mdzhd.knd_id = mdknd.knd_id</li>
<li>MDGER           tabulka vozidel, vazba na zákazníka je mdger.knd_id = mdknd.knd_id (ta zatím v datovem modelu ZZ není), ale bude urcite jako standard</li>
<li>MDKNDLST    tabulka sluzeb, takove male CRM, zadavaji se tam telefonáty, navstevy, zkratka veskera komunikace se zákazníkem, vazba mdkndlst.knd_id = mdknd.knd_id</li>
<li>MDPRSVK       Tabulka cen za jednotlive služby pro konkretniho zakaznika, vazba na zákazníka je mdprsvk.knd_id = mdknd.knd_id a mdprsvk.preis_ebene = KA (ta zatím v datovem modelu ZZ není)</li>
<li>MDART           tabulka zbozi a sluzeb, v ZZ zatím chybi</li>
<li>MDDOC          tabulka dokumentu, které se ukladaji do blobu, muze mit vazbu do vicero tabulek do mdknd, mdart, mdger</li>
</ul>
Indiv tabulky asi jen pro volvo s vazbou do MDKND:
<ul>
<li>INKNDLOGIN tabulka hesel, které vybrany zakaznik pouziva k pristupu do vybraných aplikaci VOLVA, vazba přes inkndlogin.knd_id</li></ul>

**Comment by milant007** [comment]
Toto je oficialni nazev zakaznika podle rejstriku a tak je i zaveden v DB Volva: "Budějovický Budvar, národní podnik, Budweiser Budvar, National Corporation, Budweiser Budvar, Entreprise Nationale" = 114 znaku, rozsirime v dpa_party full_name ?

**Comment by jzelenka** [comment]
Jasne, rozsiruju na 255. Takovychto zmen bude urcite vic....

**Comment by milant007** [comment]
Nasypal jsem zakazniky (807) a kontakty(email a telefon) na ne + jejich adresy(na sidlo i korespondencni) celkem se to dotklo techto tabulek: dpa_party, dpa_address, dpa_party_contact, dpa_party_contact_type, dpa_party_role, cpa_party_role_type. Tak dej vedet zda jsem dobre pochopil datovy model az si to projedes selectama, pokud ano, zitra nasypu kontaktni osoby a obchodni zastupce.

**Comment by jzelenka** [comment]
dpa_party:
 - prosim vyplnte party_category:
        FO("Person"),
	PO("Company"),
	FOP("Person (enterprising)")
     asi vsechno PO (stejne nikde neni vyplneno first_name, last_name....)
     
 - asi vyplnte tax_domicile: 'CZ'

dpa_address:
 - ok, casem pokud by byl zajem, bych mohl dodelat kontrolu na databazi adress, pak by slo delat funkce jako treba zobrazit lokaci na mape.... teda jestli je zajem zadej to jako issue, label "enhacement"

dpa_party_contact, cpa_party_contact_type:
 - ok, jedna moje chyba -  sloupecek `dpa_party_contact.ident_type_id` (vazba na ciselnik `cpa_party_contact_type`) se ma jmenovat `contact_type_id` - uz jsem to v tabulce opravil, opravte si skripty

dpa_party_role, cpa_party_role_type:
- ok

### Chybejici pole v dpa_party:
Dodelame je.

 1. platebnich podminky
   - takze defaultni platebni podminky zakaznika pro predvyplneni na fakturu? - to je jedno pole z ciselniku nebo je toho vice?  Prosim popis nebo navrhni DM

 2. měny
   - to je seznam moznych men nebo jedna mena ? Tyka se faktury nebo obecne zakaznika?

 3. jazyk(podle toho pak hovoří faktura)
   - takze defaultni jazyk zakaznika? Nebo "defaultni jazyk zakaznika pro fakturu" ?


Ostatni pole - popis nebo navrhni DM .... uvidime jestli to dame do party nebo udelame dpa_party_volvo ....

**Comment by milant007** [comment]
dpa_party:
- party_category ted vsude doplneno PO i v importnim skriptu, pripravuji import kontaktnich osob s vazbou na ty zakazniky, tam prijde FO ?
- tax_domicile jsou tam i zakaznici ze slovenska, tam se DPH neuctuje, takze u slovenskych SK ? 

dpa_address:

- Ta kontrola a zobrazeni na mape nema prioritu, casem muze byt a to uz by stejne mohl udelat nekdo z kluku

Skripty jsem upravil

###  Nova pole

Vsechny tri pole jsou pouze pro potrebu Fakturace, navrhnout defaultni menu, platebni podminky i jazyk jakym hovori FA, bude mozne na te FA zmenit pro konkretni pripad, ale aby se vzdy navrhly defaulty pri zalozeni nove. Vsechno asi vazba do ciselniku?
- U platebnich podminek se do budoucna tabulka muze rozsirit podle skonta a doby zaplaceni, nyni bych pouze udelal tyto pole: ID, nazev, doba_splatnosti(int), +  pak se muze stat, ze nekdo resi kdyz zaplatis do 5 dnu, dostanes 2% skonto, jinak STD platebni podminky jaky mas, pak by v te tabulce muselo byt jeste pole DOBA2(int), skonto(number(5,2)). Uz mam zakazniky co to pouzivaji, ale volvo ne

###  Pole ne do STD

- Proskoleni, datum kdy byl zakaznik proskolen(na co netusim)
- Datum podpisu smlouvy
- K poli vyse info, zda mu smlouvu jiz poslali nebo ne(porad se nekde ztraceji)
- Cislo objednavky(varchar) - nekteri zakaznici to chteji uvadet na fakture

###  Kam obchodni zastupce?

- Nyni maji vlastni pole Zastupce1 a Zastupce2, ale asi bych to udelal jako vazbu a zalozil je dpa_party, nebo?

**Comment by milant007** [comment]
Naimportoval jsem Kontaktni osoby

- dotko se to stejnych tabulek + dpa_party_rel a cpa_party_rel_type, to jsem provazbyl mezi zakaznikama a kontaktnima osobama, tak zkontroluj zda je to tak spravne
- pak dosypu Obchodni zastupce (dpa_party)

**Comment by jzelenka** [comment]
kontaktni osoby jsou asi dobre, jenom:
 - ve vsech party je v title_after 4-mistne cislo, co to? idecko z MD?
 - v party - kontaktni osoby v ico 5-mistne cislo ? to same?

Koukal jsem ze jsi zavedl do cpa_party_contact_type taky:
 `zasílání faktur`
`upozornění email`
`zaslat registraci`

premyslim, jestli na takoveto on/off prepinace nezavest novou tabulku...

Dale nazvy ve sloupecku `name` v tabulkach jako je:

    cpa_party_contact_type 
    cpa_party_role_type 
    cpa_party_rel_type

by mely byt anglicky - jsou lokalizovatelne - viz https://github.com/zauzoo/app/wiki/Lokalizace

-

**Comment by jzelenka** [comment]
Jinak si klidne pro potreby migrace pridavej vlastni policka - aplikaci policka navic neovlivni (pokud nejsou not null) - jen je nejak rozumne nazvy (treba temp_xxxx) - muzou tam pak zustat dlouho.

**Comment by milant007** [comment]
- vsechny name v tabulkach xxx_type jsem prelozil do EN
- souhlasim aby pro pole z cpa_party_contact_type s hodnotou 1/0(true/false) byla vlastni tabulka
- vytvorim si vlasni sloupce temp_xxx a presunu tam ty informace, ktere uvadis, jsou to IDcka z MD

**Comment by jzelenka** [comment]
Pridal jsem do party pole:
- `default_currency` a odpovidajici ciselnik `cpa_currency`  (naplnil jsem ho)
- `default_lang` a odpovidajici ciselnik `cpa_language`  (naplnil jsem ho)
- `default_payment_cond_id` a odpovidajici ciselnik `cin_payment_cond`

Dale jsem pridal tabulku `dpa_party_feature` a jeji tabulku typu featur `cpa_party_feature_type`
kam prosim presun ty 3 typy z kontaktu.

**Comment by jzelenka** [comment]
Co se tyce policek:
 - Proskoleni, datum kdy byl zakaznik proskolen(na co netusim)
 - Datum podpisu smlouvy
 - K poli vyse info, zda mu smlouvu jiz poslali nebo ne(porad se nekde ztraceji)

Otazka jestli pridat jako 3 policka na Party nebo zalozit zarodek moznych budoucich modulu:

#### Skoleni
tabulku skoleni - dalo by se tam jedno skoleni "Volvo" a 
a tabulku party-skoleni, kde by bylo to datum

#### Smlouvy
tabulku smluv - dala by se tam jedna smlouva "Volvo" a 
a tabulku party-smlouva, kde by bylo to datum podpisu smlouvy a priznak poslano / neposlano

**Comment by milant007** [comment]
### Naplnil jsem vsechno nanovo
- dpa_party zakaznici maji vyplena pole default_currency, default_lang, default_payment_cond_id
- dpa_party ma nova pole temp_md_knd_id, temp_md_zhd_sid kde si ukladam IDcka z puv tabulek
- zaskrtavadla jsem prehodil na dpa_party_feature, zde nevim zda pouze existence znamena true a kdyz neni tak false? pro jistotu jsem dal do comment '1'

### Skoleni = Sluzby

- Udelal bych globalne tabulku sluzeb, neco jako CRM. Zadam tam datum, typ operace(z ciselniku napr. Skoleni, navsteva, telefonat, upominka platby, atd.), text. Tady se toho da vymyslet strasne moc ale pro zacatek to takto staci.
- Kdyz nad tim premyslim, tak i smlouva ma datum a operace by se jmenovala Smlouva, text muze byt co se s ni zrovna deje, akorat jeste pridat BLOB pro scan te smlouvy(u upominky by to bylo to PDF co se posilalo zakaznikovi). Mozna jeste nejake pole "pripomenout_dne" aby clovek co to zadal kdyz toto pole vyplni dostal link do emailu na toto CRM aby se k tomu nezapomnel vratit coz plati pro ty smlouvy, upominky dalsi telefonat... 
- Na druhou stranu ty mas mozna vetsi zkusenosti s CRM tak mi to rozcupuj... :-) Mozna BLOBy skladovat na jednom miste s relaci do vybranych tabulek? (dpa_party, sluzby, atd...)

**Comment by jzelenka** [comment]
`dpa_party_feature` - ano, pouha existence znamena true. Kdyz to konci tak se smaze. Pokud by byla potreba pamatovat si ze to kdysi mel a ted uz ne, tak se to nesmaze a vyplni se datum valid_to. Stejne tak se muze vyplnit datum valid_from, pokud nas zajima od kdy to ma.
Popis viz https://github.com/zauzoo/app/wiki/Datov%C3%BD-model#specialni-sloupce

Comment je proste comment, nejaka dodatecna informace, vetsinou bude nevyplneny.

Na Skoleni = Sluzby se jeste podivam a neco navrhnu.

**Comment by milant007** [comment]
Naimportoval jsem obchodni zastupce
- tim jsem nasypal asi vsechno co ted slo do stavajiciho DM
- zbyva jeste evidence vozidel s vazbou do dpa_party(zakaznici),  karty zbozi/sluzeb, cenik(jak obecny, tak individualni) za zbozi/sluzby

**Comment by jzelenka** [comment]
Vloz prosim do Party Volvo Group Czech Republic, s.r.o. 
Nemusi mit zadnou roli, takze nebude videt v zadnem gridu.  Casem pridame do Party / Administration grid All Parties, kde videt bude.

Dale, ted je v party customer Volvo Group Slovakia, s.r.o.  s tenant_id = 1.  Az budeme migrovat slovensko, tak pribude Volvo Group Slovakia, s.r.o. s tenant_id = 2 (SR)

Takze tam bude 2x. Analogicky pro Volvo Group Czech Republic, s.r.o. 
To asi tak nevadi. Jednou ma roli customer, jednou ne...

Alternativne by slo temhletem dat tenant_id = 0 a celej Party modul nastavit jako SHARED (nyni je PRIVATE) viz https://github.com/zauzoo/app/wiki/Multi-tenancy

S tim si pak muzeme pohrat u dalsich zemi.

**Comment by jzelenka** [comment]
doplnil jsem do `script/create/03_data_party_reference_tables.sql` ciselnikove tabulky v party (cpa_*)
prosim v pripade prirustku udrzovat...

**Comment by milant007** [comment]
Pridal jsem VOLVO vcetne adresy a kontaktnich udaju do tenanta 1 s priznakem owner. Skript jsem pushnul do ImportMD.

Behem importu mi doslo, ze postradam tabulku na bankovni spojeni 1:N(zakaznik muze mit vice uctu) do dpa_party. V tomto pripade se bankovni spojeni vyuzije do layout faktury.
Tabulka bankovnich spojeni by mela obsahovat(premyslim, zda to ma smysl popisovat nekomu kdo se v tom pohybuje denne :-) ):
- predcisli(vcetne kontroly modulo)
- cislo uctu(vcetne kontroly modulo)
- cislo uctu(vcetne kontroly moduly)
- nazev banky
- IBAN
- SWIFT
- Mena

**Comment by jzelenka** [comment]
drobne jsem upravil 6ImportOwner.sql - idecka do ciselniku mam natvrdo v 03_data_party_reference_tables.sql  (nikoliv max() + 1)  , protoze je odkazuji v kodu, musi byt porad stejne.

dej si `git pull`

**Comment by jzelenka** [comment]
bankovni spojeni pridano.

**Comment by milant007** [comment]
banku a cisla uctu jsem vlozil a upravil skript Import Owner a pushnul na git. 
jen jeden dotaz, VOLVO jako adresu banky na FA uvadi ne sidlo ale adresu pobocky, tak nevim, zda nedat adresu jeste do bank_account?

**Comment by jzelenka** [comment]
budeme davat do bank i pobocky,
pridal jsem tam bank_type = MAIN, BRANCH   (not null)
a parent_bank_id =  pro typ BRANCH bank_id materske banky, jinak null

**Comment by milant007** [comment]
upraveno v datech i ve skriptu
