### ISSUE TITLE
Madarsko - delivery date na FA

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#21]
Na FA jsou v HU vyžadovány tři datumy:
-          Invoice issue date
-          Due date
-          Delivery date: not an exact date but depends on different parameters. See my summary in below excel
 
 
![hu_delivery_date](https://cloud.githubusercontent.com/assets/13977376/12234856/2a26910e-b870-11e5-92eb-8e4652f5c356.jpg)

 
As you see, there is two main types: 
1.)    Delivery date =  Issue date – if the issue date and the due date is before the last day of the period
2.)    Delivery date = due date – if the due date is later than the invoiced period last day

**Comment by jzelenka** [comment]
Neni z toho uplne jasny jestli to pokryva vsechny moznosti, je to naprogramovane takto:

if  due date is later than period last date 
then  due date
else issue date
