### ISSUE TITLE
Co je treba dodelat pro potreby 1. fakturace

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#23]
Idealne dodelat v tomto poradi, aby mohli upravovat podklady a az pak se budou hrabat ve fakturaci:

1. Moznost vazbit a mazat auta u jednotlivych zakazniku
2. Moznost vazbit a mazat produkty u jednotlivych aut(asi by bylo idealni do te same zalozky nacpat i cenotvorbu pokud ma auto indiv cenu)
3. Cenotvorba, moznost zadat cenu v detailu zakaznika nebo detailu vozidla. Cena v detailu produktu tedy nejvyssi v hierarchii asi nehori, to je par produktu, kde to pripadne insertnu primo do db vzhledem k tomu ze nemame hotovy ani detail produku.
3a. Možnost provazbit zákazníka s kontaktní osobou/prodejcem. Chtějí si nastavovat role pro zasílání upozornění, zasílání FA a chtějí dozadat kontaktní osoby.
4. V gridu produktu alespon zakladni cenu zobrazit kdyz uz nepujde editovat, aby ji bylo videt.
5. Formular FA + polozky FA
6. Tisk/generovani PDF, asi kdyz zjistej ze se nejaka FA vygenerovala spatne, aby si ji pripadne mohli upravit, hromadny tisk asi az pozdeji

Pripadne jak mi budou dochazet nove veci, budu zde doplnovat.

**Comment by jzelenka** [comment]
1) je hotove. Výběr party na detailu auta je udelany postaru, jako na userovi (ten novy - normalni policko s autocomplete ted nestihnu). Nove auto jde delat z gridu aut, z detailu auta a z detailu customera.  Pro posledni dva se prekopiruje customer. 

Z detailu aute lze navic copy auto.

Maze se pouze z detailu auta.

Navazbeni auta na jineho customera se dela z detailu auta - disconnect, vybrani jineho customera a save.

**Comment by jzelenka** [comment]
je hotove 2. - z detailu auta se muzou pridavat, mazat a editovat produkty.

**Comment by jzelenka** [comment]
opravil jsem price_level v dpr_price_component - potrebuju tam ten String

update dpr_price_component set price_level = 'PRODUCTCUSTOMER' where price_level = '2';
update dpr_price_component set price_level = 'PRODUCTVEHICLE' where price_level = '1';

**Comment by milant007** [comment]
Opravil jsem si to v importnich skriptech, jen POZOR, tenant 2 pouziva i price_level = '3' tedy 'PRODUCT', tak asi i tady to chce update. ale nevim zda chces pouzivat primo tento string, tak nechavam na tobe.

**Comment by jzelenka** [comment]
jo jasne, nevsiml jsem si,
update dpr_price_component set price_level = 'PRODUCT' where price_level = '3';

cenotvorba jeste asi dnesek zabere...

**Comment by milant007** [comment]
Prosim, zitra to musi bezet, jinak me uskrtej!

**Comment by jzelenka** [comment]
bude, 
ta editace detailu (produktu na vozidle) je OK?

**Comment by milant007** [comment]
prijde mi to ok, vic ukaze cas

**Comment by jzelenka** [comment]
je tam cenotvorba
Podarilo se udelat in-place search vozidla a party (jestli je to takto dobre, muzeme predelat vyber party na vehicle...)

Ale neni deploynuta (nefunguje me tady VPN),  musis udelat deploy: http://vpn.flexidata.cz:8099/
a spustit oba zauzoo joby - DEPLOY FE a DEPLOY APP

co dal? faktura ?

**Comment by jzelenka** [comment]
je tam oprava cenotvorby - uz se nekontroluje vyplneni customera pri urovni PRODUCTVEHICLE
je treba deploy ZAUZOO FE

**Comment by jzelenka** [comment]
bod 3a (vazbeni parties) je hotove

**Comment by milant007** [comment]
chtel jsem otestovat, ale asi jeste neni v produkci?

**Comment by jzelenka** [comment]
Melo by byt, zkus F5

**Comment by jzelenka** [comment]
Ty vazby by se daly resit jeste tak, ze by v toolbaru byly dve tlacitka - "Pridej vazbu od" a "pridej vazbu do" a na samotnem formu pak jen uz ta protistrana.

Jenze v okamziku zmacknuti toho tlacitka by uz vubec nevedeli co maji vybrat. Takhle tam maji alespon napovedu...

Jeste by slo predvyplnovat From / To podle role (Customer = To, Contact, SR = From, kdo ma vice roli tak nechat treba From. Nebo To :).
Nyni je incialne From.

**Comment by milant007** [comment]
Ja to s nima jeste resil telefonicky a spis jde o to, jak jsou zvykly delat v MD. Pry to zatim mame nechat a uvidi se.

Co je pry ted trapi nejvic, je, kdyz edituji nekolik formularu a pak se chteji vratit do gridu. Takze bych ted primarne udelal tlacitko UP aby se vratilo do zafiltrovaneho gridu a nemusel bud dat nekolkrat back, nebo opet otevrit grid a znovu filtrovat.

**Comment by jzelenka** [comment]
Je to tam vsechno:
- tlacitko UP - dokonce nested, tj. jdu na zakazniky, zafiltruju, jdu na kartu zakaznika, skacu horizontalne mezi zakazniky, jdu na vozidlo zakaznika, skacu horizontalne mezi jeho vozidly, dam up - jsem na zakaznikovy, dam znovu up - jsem na seznamu zakazniku
- confirm dialog pri opusteni editovaneho detailu
