### ISSUE TITLE
Tenant defaults

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#24]
- bylo by dobrý pokud má uživatel více tenantů mu nastavit default tenanta, který se bude nabízet po zadani loginu
- Pokud mam vice tenantu na uzivatele, tak mit moznost se mezi tenanty prepinat bez toho abych musel davat logout a znovu se prihlasovat

**Comment by milant007** [comment]
Cau, jeste k tomuto bodu pridavam dalsi pozadavek na default hodnoty. Je potreba aby pri zakladani nekterych ciselniku byla moznost nastavit default hodnoty pro nektera pole:

- nyni ten pozadavek vznikl na SK v karte zakaznika. chtej tam defaulty pro menu, jazyk, narodnost, a Dan...
- samozrejme ze to pak bude trebas nutne(Volva se to netyka) i v karte Product, kde budu chtit default hodnoty pri zakladani na DPH v jaky sazbe, mnozstevni jednotky...

**Comment by jzelenka** [comment]
takze ta defaultni hodnota bude per policko a tenant ?

**Comment by milant007** [comment]
Ano, ale muze nastat i situace, kdy je to zavisle na konkretnim uzivateli.
- pokud se uzivatel stara pouze o zahranicni zakazniky, tak muze mit jinou vychozi menu atd. Nebo pozdeji v pripade skladu muze mit kazdy uzivatel jiny defaultni sklad, jine stredisko v zakazkach, atd. 
Pro ted urcite staci na tenantovi, ale do budoucna to muze byt zase hierarchie uzivatel a pokud neni tak tenant.

**Comment by jzelenka** [comment]
Udelal jsem moznost nastavit defaultniho tenanta a hlavne moznost prepnout tenanta bez znovuprihlaseni (v menu prihlaseneho uzivatele vpravo nahore).

Navic to umoznuje mit ruzne tenanty v ruznych oknech aniz by se vzajemne rusily. Lze tedy soubezne pracovat na vice tenantech. Tahle posledni vlasnost byla nejpracnejsi....

Pushnuto.

Nechavam otevrene kvuli defaultum na polickach v zavislosti na tenantu a uzivateli.

**Comment by milant007** [comment]
Jo, je to super usetri mi to neskutecny prace, to opetovny prihlasovani a odhlasovani me privadelo k silenstvi...
Jeste bych mel jeden navrh, ale pokud by to bylo pracny, tak nic - je to jen pro nas, uzivatel to nepozna. Ty tenanty sesortovat podle abecedy, pribude jich jeste par a pri prihlasovani/prepinani se v tom bude spatne orientovat....

**Comment by jzelenka** [comment]
ok, neni problem

**Comment by jzelenka** [comment]
pushnuto sortovani tenantu pri loginu i pri zmene.

**Comment by jzelenka** [comment]
zaviram, defaultni hodnoty viz #102
