### ISSUE TITLE
Ztrata relace kontaktni osoba -> zakaznik

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#25]
pokud mam vazbu z kontaktni osoby na zakaznika a te kontaktni osobe pridam dalsi roli, ja zkousel Email invoice, tak se ztrati ta vazba na zakaznika.

**Comment by jzelenka** [comment]
Tohle je celkem pruser,  pri jakemkoliv save Party se smazou vsechny vazby te Party....

Opravim to spolu s dodelanim editace vazeb (bod 3a).
Dnes vecer, do te doby party vubec needitovat..

**Comment by jzelenka** [comment]
Editaci vazeb jsem dneska nestihl, tak jsem alespon opravil tu ztratu relaci pri savu Party.
Udelej deploy APP i FE.
