### ISSUE TITLE
Navazovaní vazeb - search party na vehicle i na ownera, zobrazit vehicle grid na party s roli owner

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#26]
Při vazbení v detailu auta (pokud ho zakládám z menu Assets Vehicles) na party se nebízejí party i z jiných tenantů. Takže když napíšu volvo, tak mi tam skočí celkem 6 možností, ale v tenatu 2 je volvo pouze 1x. Celkem je jich 6. 
a koukám, že to dělá i jinde, takže asi tím pádem všude.

**Comment by jzelenka** [comment]
hotovo,
navic, pri vyberu party na vozidle, se nabizeji pouze customeri (= parties s roli Customer )

**Comment by jzelenka** [comment]
a pri vyberu party na Prices taky pouze customeri

**Comment by milant007** [comment]
jeste k tomu mam dotaz, potrebovali si priradit auto na Volvo SK cili role owner. takze jim to dnes neslo, ja priradil Volvu SK jeste roli customer, pak to slo. akorat nevim, zda to nekde nebude svinit? nebo pridat do toho vyberu jeste roli owner a volvu sk tu roli zase vzit zpet?

**Comment by jzelenka** [comment]
No to je otazka.

ta role owner asi tedka v kodu nic nema (zadnou logiku).
Zavedl jsem ji abychom tu party "poznali"

Roli customer se ridi:
- zobrazeni zalozek Vehicle, Invoice, InvoiceItem (obe navazana pres billedTo)
- filtr v party u Vozidla a Cenotvorby

Takze kdyz mu nechame customer, tak to asi ted nevadi, ve fakturach neuvidi nic (je vsude v billedFrom, ale asi nikde v billedTo, pokud si tedy nefakturuje sam na sebe, coz je snad blbost)

Na detailu faktury ale, pri vyplnovani billedTo, ho pak bude mozne vybrat - tam bude urcite met byt role customer, coz je spatne.

Kdyz mu roli customer nenechame, tak musim zmenit:
- povolit zobrazeni zalozky Vehicles na Party i na roli Owner
- filtr na search na party na Vehicle povolit i ownera, na cenotvorbe asi ne?


Asi je spravnejsi mu nechat roli ownera a provest ty upravy. Kdyz mu dame roli customer, tak ho proste uz od customera nerozlisime... coz vadi asi jen trochu (viz to nabizeni v billedTo na fakture), ale uz to nebude resitelne...

Co ty na to?

**Comment by milant007** [comment]
pokud to neni moc prace, tak souhlasim. Jinak bych se to na vyprd a nechal volvo SK v obou rolich.

jen jeste upozornuji, ze do budoucna budou doklady(výdej do spotřeby, inventura, atd.) které budou mít stejnou logiku a asi i formular jako je zadávání do FA, ale tam bude muset být možnost zadat ownera.

**Comment by jzelenka** [comment]
- povolit zobrazeni zalozky Vehicles na Party i na roli Owner
- filtr na search na party na Vehicle povolit i ownera

**Comment by jzelenka** [comment]
hotovo. Je mozne odebrat z Volva ownera roli Customer

**Comment by jzelenka** [comment]
Logika u jednotlivych roli je popsana na:

https://github.com/zauzoo/app/wiki/DM-Party#dpa_party_role-partyrole
