### ISSUE TITLE
Zadávání poznámky do Party

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#27]
V SK si chtějí k některým zákazníkům/kontaktním osobám zadávat nějaké vlastní poznámky. Navím zda na to udělat pole v DB dpa_party.comment nebo nějakou extra tabulku kam se budou zadávat jak poznámky, tak třeba dokumenty vč. BLOBu? A tato tabulka by byla poznámkami jak pro party, tak pro auta, produkty a trebas i FA?

**Comment by jzelenka** [comment]
uz je hotova tabulka pro party - pouze pro party a pouze poznamky....
asi to nechame vsechno zvlast (kazdy hlavni objekt svoji tabulku pro poznamky a dokumenty taky jinde...).


btw. maily prave prisly... tak jim jen nekde vysely..

**Comment by jzelenka** [comment]
teda GUI jeste neni.

**Comment by jzelenka** [comment]
hotovo

**Comment by milant007** [comment]
kde to najdu? chtel jsem vyzkuset...

**Comment by jzelenka** [comment]
plusko v menu.
