### ISSUE TITLE
Chyba při generování faktur

### ISSUE THREAD

**Issue by MichalZZ** [zauzoo/app#33]
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: column invoice0_.to_permenant_city does not exist

Nejspíš překlep v názvu.

Dnes se fakturuje z Volva. Potřebujeme to ASAP.

**Comment by jzelenka** [comment]
mas aktualizovane zdrojaky? tohle by melo byt opravene koncem minuleho tydne.

**Comment by jzelenka** [comment]
`git pull`

**Comment by MichalZZ** [comment]
Měl jsem starou verzi, ale teď nastal další problém.

org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.hibernate.SessionFactory]: Factory method 'sessionFactory' threw exception; nested exception is org.hibernate.MappingException: Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType

**Comment by jzelenka** [comment]
mrknu na to

**Comment by milant007** [comment]
Prosim te, dej tomu HIGHEST PRIORITY! Potrebuji vygenerovat 200 FA ASAP, aby mohli v SK zkontrolovat a meli jsme cas na pripadne opravy.

**Comment by jzelenka** [comment]
Jak to delate, co spoustite? nejde me to zreprodukovat.
Taky jste nekomitnuli signature_hu.png v tool repo - pada me to ze neexistuje

**Comment by MichalZZ** [comment]
mvn -Dtest=InvoiceTests#printInvoice test

**Comment by jzelenka** [comment]
ok, tak commitnete vsechno v app a tool repo, treba to signature_hu.png

**Comment by jzelenka** [comment]
a dej sem celej stacktrace z ty chyby.

**Comment by MichalZZ** [comment]
Vyřešeno. Problém byl ve mě.

**Comment by jzelenka** [comment]
:), tak priste jeste Close Issue.
