### ISSUE TITLE
Pole v dpa_party pro potreby prenosu do ucetnictvi?

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#34]
Vznikl pozadavek na pole pro Prevod do Ucetnictvi v HU. My jsme toto jiz v SK vyresili tim, ze jsme zalozili contact typu Parma coz je v SK parovaci znak obchodnich paartneru pro prenosu FA do ucetnictvi. 
Nyni chteji to same Madari, kteri to pole nazyvaji iScala. Muzem jej zase zalozit v kontaktech jako je to v SK, ale obecne musim rici, ze pokud budem posilat offline soubor do ucetnictvi jakehokoliv zakaznika, tak vsichni jiz sve obchodni partnery v ucetnictvi maji pod nejakym kodem a ten musime posilat. Takze je otazka zda na to neudelat pole primo v dpa_party?
Pokud ne tak prosim o vytazeni kontaktu Parma do gridu Customers. tedy podminka ze contact_type_id = 7 pokud je vyplneno.

**Comment by milant007** [comment]
jo a stejne tak chteji tuto informaci v gridu Faktur kde si to jiz samy exportuji do xls, ale toto jim vyrazne pomuze pri nejake kontrole atd...

**Comment by jzelenka** [comment]
Pridal jsem funkcnost PartyFeature. Je to podobne jako PartyContact, ale:
- PartyFeatureType neni ciselnik, ale enum, tj. pridava se programove a kazdy featureType ma vlastni definovane GUI, tj. svuj formular.
- v jednom PartyFeature muze byt vice policek
- pridavaji se pres plusko jako PartyNote, Na party muze byt od kazdeho featureType maximalne 1.
- nyni jsem udelal 2 PartyFeatureTypes:  
  -  ADDITIONAL_IDS, kde je nyni policko Account Matching ID (muze tam byt v budoucnu vice parovacich idecek), do ktere ho jsem zmigroval contactType 7 Parma a tyto contakty smazal. Account Matching ID se dale kopiruje do faktury do policka accountMatchingId. A je dostupne v Party gridech jako Accounting ID.
  - VOLVO_LOGINS, kde jsou policka pro loginy do jinych systemu, pozadovane v #14
