### ISSUE TITLE
co se zaokrouhluje podle monetary rounding

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#35]
uz na InvoiceItem ? a pokud jo, tak uz unitPrice? nebo az basePrice? nebo az priceWithoutVat ?
nebo az soucty na Invoice? a zase, pokud jo tak co ....

Nejjednodussi by bylo kdyby se zaokrouhlovalo hned nebo rekneme od basePrice na InvoiceItem (aby unitPrice z ceniku mohla byt jina).

**Comment by milant007** [comment]
Kdyz to vezmu podle zkusenosti z Heiru, tak na Invoice Item se zaokrouhluje na 5 desetinnych mist vsechno, unit price, base price., atd. Jde jim prave oto urcit cenu za jednotku. Kdy jeden metr kabelu je tak mala jednotka, ze musi mit tolik desetinnych mist. Pri cene za kilometr by to bylo v pohode, tam by to bylo prave na ty dve desetinna mista, ale oni proste chteji cenu za metr.
Hlavicka FA pak uz je pouze na dve desetinna mista, uz je to cislo co se zobrazuje na FA jako suma. A to pak jeste muze byt finalni zaokrouhleni cele FA na jedno desetinne misto nebo na cele cislo. k tomu pak slouzi radek na Fakture _halerove vyrovnani_.
Halerove vyrovnani se musi delat vzdy, kdyz je prodej faktury za hotove neb uz nemame halere. Ale dokud byly v CZ halere na jedno desetinne misto, tak se delaly FA za hotove prave na jedno. Cili v zemich kde nemaji EUR, tak muze nastat defakto cokoliv.

**Comment by jzelenka** [comment]
Takze jsem spustil nasledujici skript:

    alter table din_invoice
        add column penny_adjustment numeric(18, 8);

    alter table din_invoice
        add column total_adjusted_price numeric(18, 8);

    update din_invoice set penny_adjustment = 0, total_adjusted_price = total_price;

    alter table din_invoice
        alter column penny_adjustment set not null;

    alter table din_invoice
        alter column total_adjusted_price set not null;


Nyni (pro Volvo) je zaokrouhleni na fakture (total_price) a na halerove vyrovnani vzdy stejne (na 2 desetinna mista),  tj. penny_adjustment  = 0 a  total_adjusted_price = total_price

Nazval jsem to takto, protoze jsem chtel nechat price_to_pay pro nejake pripadne castecne splacene faktury...

Uprav si pripadne skripty

**Comment by milant007** [comment]
skripty upraveny

**Comment by milant007** [comment]
A uz je to tady, Madari chtej zaokrouhlovat HUFy na fakture. tedy xxx_lcy. EURa zjistujem zda chteji podle zaokrouhleni prepocitat kurzem nebo nechat tak jak jsou.

**Comment by jzelenka** [comment]
takze pro lcy:


    alter table din_invoice
    add column penny_adjustment_lcy numeric(18, 8);

    alter table din_invoice
    add column total_adjusted_price_lcy  numeric(18, 8);

    update din_invoice set penny_adjustment_lcy = 0, total_adjusted_price_lcy = total_price_lcy;

    alter table din_invoice
    alter column penny_adjustment_lcy set not null;

    alter table din_invoice
    alter column total_adjusted_price_lcy set not null;

**Comment by milant007** [comment]
skripty pro generovani faktur upraveny, madarske faktury zaokrouhleny. 
Jindro muzees upravit report pro HU

**Comment by jzelenka** [comment]
Udelal bych konfiguraci haleroveho vyrovnani na cin_payment_type, tj. pridal bych tam sloupce penny_rounding a penny_rounding_lcy.

cin_payment_type by pak muselo byt rozkopirovane pro vsechny tenanty (nebo nekde jen pro tenantGroup mozna, ale u Volvo az na tenanty) a u volva, kde je jen Account Transfer by vsude bylo rovno 2, akorat u HU by penny_rounding_lcy = 2.

Pokud bychom nechteli cin_payment_type rozkopirovavat tak by se musela udelat nova tabulka jako vazba na tenant a tam by bylo to zaokrouhlovani. Ale vzhledem k tomu ze obcas muzou byt ruzne payment type pro ruzne tenanty, tak by se to stejne obcas muselo rozkopirovavat.

?

**Comment by jzelenka** [comment]
@milant007 vsiml sis dotazu vyse?

**Comment by milant007** [comment]
zrovna to mam rozepsany

**Comment by milant007** [comment]
pujde to tak, ze tam nechame i ten cin_payment_type.tenant_id = 0 ? a pouze tam kde to je jinak tak zalozime indiv radek pro konkretniho tenanta/tenant_group s tim ze maji vyssi prioritu a nebo to budem muset zakladat vsude a tenant_id = 0 smazat?

kdyby se tenant_id = 0 nemusel smazat, jak pisu tak by to stacilo. 

Jinak kdyz nad tim premyslim, nevim zda by nemela byt nejaka tabulka parametru pro kazdeho tenanta, kde by toto bylo pokupe, protoze urcite se objevi dalsi parametry co budou indiv podle tenantu... ? MDcka to tak maji, na druhou stranu se v tech parametrech stejne nikdo nevyzna. :-( Takze vlastne nevim.

**Comment by jzelenka** [comment]
Aj, problem je jeste vetsi.
Nyni nemame v ciselnicich tenant_id v PK. Takze by tady "Account Transfer" mel ruzne IDecka. Coz nemuze byt, protoze na ty IDecka budou v kodu ruzne podminky. Tak uz to je treba v role_type nebo rel_type, jen protoze zatim maji vsichni tenanti vsechny typy tak se na to neprislo...

Kdyz dame tenant_id do PK, tak prijdeme o cizi klice, protoze tenant_id datove tabulky a tenant_id ciselnikoveho radku muze byt ruzne (0, tenantGroup).

napadaji me 2 zpusoby,

zpusob A)
- v ciselnicich pridat tenant_id do PK
- obetovat FK
- mozna pridat logiku na tu prioritizaci, tedy aby se pro kazde IDecko vybral radek s nejvetsi prioritou tenanta (tenant, tenantGroup, global) pokud jich je vic.

zpusob B)
- v ciselnicich zrusit tenant_id
- kazdy ciselnik bude mit dalsi vazebni tabulku na tenanta (tenantId, tenantGroupId, nebo 0)
- parametry pak budou na vazebnich tabulkach.


Teda nevim co je lepsi

**Comment by milant007** [comment]
Problemu rozumim. 

Zpusobum reseni asi ne na 100%, tak mozna by mi pomohl call na vysvetlenou. Z toho co jsem snad pochopil bych se priklanel k Bčku.
