### ISSUE TITLE
Skupiny tenantů - myšlenka jak to oddělit

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#37]
Napadlo mě, že pokud bych chtěl používat skupiny tenantů tak by se to dalo udělat tak, že v tabulce tenant by byla možnost definovaní pro každou tabulku jakého tenanta má brát. Když nebude nic vyplněné bude brát standardně toho svého a nebo 0. Ale pokud budu chtít u Volva mít vlastní produkty jen pro Volvo tenanty, tak bych u Volvích produktů nastavil třeba tenant id z nuly na jedničku a pak pro SK a HU v definici tco_tenant.dpa_product_table = 1. Pak by prostě i HU a SK při editaci/vytváření těchto položek vždy vkládali do tenanta 1.
Pokud bude v definici tco_tenant.dpa_product_table = null pak bude princip stejný jako doposud.

Co ty na to?

**Comment by jzelenka** [comment]
To by asi fungovalo, ale mam strach ze pak bude strasne slozite uvazovat nad tim co se vlastne deje.

Uz dneska se na urovni tabulky (entity) nastavuje tenancyType GLOBAL ( = 0), PRIVATE ( = currentUser.tenantId), SHARED (  in (0, currentUser.tenantId) )

Dale tam jsou 2 implementace:

`HQL, criteria API`:   where podminka se doplnuje na vsechny tabulky, ale tenancyType se ignoruje a vzdy se pouzije in (0, currentUser.tenantId)

`SqlQuery` (grid a nektere dalsi selecty (zbytek pouziva HQL nebo to criteria API)) : where podminka se doplnuje presne podle tenancyType jak uvedeno vyse, ale pouze na hlavni entitu gridu nebo toho searche - zatim to nevadilo.

Takhle divne je to udelane z technickych duvodu, pokud bude potreba da se to dotahnout (jako treba presna podminka pro HQL nebo where podminky pro dalsi tabulky u SqlQuery)

Takze kdyz by se tam pridalo to tvoje tak uz to bude pekne slozite....

Az to nastane tak se rozhodneme jestli pouzijeme:
- tohle
- tenantGroup, kde by se tenantGroupId muselo pridat do vsech tabulek
- zakodovat tenantGroup do tenantId (treba by to byl string (3_5) nebo cislo po tisicich (div 1000 = tenantGroup)
  - tedy bude problem s porovnanim na tenantGroup protoze se bude muset vyparsovat tenantGroup, tedy pouziti vyrazu ve where podmince.... ale treba by pomohly indexy nad vyrazem (http://www.postgresql.org/docs/9.1/static/indexes-expressional.html) a zase toho nebude tolik.

**Comment by jzelenka** [comment]
Ted me napadlo:
- zrusit tenancyType
  - tedy vsude pouzit  `in (0, currentUser.tenantId)` a ridit to jen tim co se vyplni - to vicemene stejne tak je
- zavest tenantGroup, ale jen na tenantovi, tj. kazdy tenant bude patrit do jedne tenantGroup.
- na tabulkach nechat jen tenantId
- tenantGroupId davat hodnoty treba od 1000000
- podminku upravit na `in (0, currentUser.tenantId, currentUser.tenantGroupId)`

Takze pro volvo zavedeme tenantGroup VOLVO tenantGroupId = 1000000
a produktum dame tenantId = 1000000
a bude to fungovat....

Tohle je pro me nejjednodussi a zda se ze to bude fungovat...

**Comment by milant007** [comment]
muze byt, ale je ti jasny ze to bude fungovat jen do 999.999 tenantů v DB. :-) 

Akorat kdyz dam novy produkt, co se mu priradi za tenant_id ?

**Comment by jzelenka** [comment]
nyni v GUI vyber tenancyType pri vkladani noveho radku nikde neni, takze se prirazuje podle tenancyType entity, kterou vidis na Administration / Entities.

Product ma TENANTGROUP, a vsichni tri tenanti volva maji tenantGroup Volvo s tenantGroupId = 1000000. 

Takze se priradi tenant_id = 1000000

Nasazeno.

**Comment by milant007** [comment]
funguje, ikona palec nahoru :-)

a jeste dotaz, kdyz bych si chtel zalozit jeste jednoho tenanta - MultiData a pripravit si skripty pro presypani vlastni produkce, abych to testoval i na sobe. Co mam udelat pro to, aby producty byly oddeleny?

**Comment by milant007** [comment]
uz to mam presypane, takze nemusis odpovidat

**Comment by jzelenka** [comment]
jo, mas to dobre
