### ISSUE TITLE
ruzne vybirani v gridu - export x Bulk Actions

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#40]
Export nyni vybere vsechny radky v gridu
Bulk Actions vezme jen ty zaskrtnute.

Co to sjednotit:
Kdyz neni zapnute zaskrtavani berou Export i Bulk Actions vsechny radky v gridu
Kdyz se zapne zaskrtavani berou Export i Bulk Actions pouze zaskrtnute radky

Co me napada proti, ze by nekdo mohl spustit nejakou nebezpecnou Bulk Actions na moc radku - ale vsechny bulk actions, ktere neco delaji budou mit jeste Dialog - jako dneska ty ceny - i kdyby tam nebylo potreba nic vyplnit a bylo to tak jen pro potvrzeni.

?

**Comment by milant007** [comment]
Souhlasim, udelej to tak. Me to uz taky napadlo, ale neodvazil sem se to navrhnout. :-)

**Comment by milant007** [comment]
jeste jedna vec, kdyz se budou ty data zpracovavat, pokud tam bude nejake order by, tak aby se ty zaznamy zpracovaly v tom poradi. Napr. chteji pri hromadnem generovani FA mit cisla faktur podle nazvu zakaznika pro nejake zpetne odkontrolovani.

**Comment by jzelenka** [comment]
hotovo,
jo, taky je opravane zadavani cisel a datumu do podminek gridu a da se vyhledavat podle stringovych rad (from - to)

**Comment by milant007** [comment]
jeste mi to vyhnilo na vyhledavani from - to u datumu: Server error 500 MdException: Expected JSON Date String, but got 1.3.2016

**Comment by jzelenka** [comment]
to je divny, me to chodi:

![image](https://cloud.githubusercontent.com/assets/1957955/14451639/f9ffa7ac-0088-11e6-9424-4595d17826ad.png)

**Comment by jzelenka** [comment]
refresh?

**Comment by milant007** [comment]
jo, jsem hnup, vsechny uzivatele takhle prudim a sam to neudelam... :-(
