### ISSUE TITLE
Indiv grid error

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#42]
Pokud se prihlasim do ZZ dvakrat jako ten samy uzivatel, ale jednou jako "petr01" a vytvorim si vlastni grid, tak pote, kdyz se tam prihlasim jako "PETR01" tak ten grid nevidim, cili je tam nekde nejake case sensitive...
V definici gridu jsem si chtel nastavit pole Teplice(to indiv pro Penax) ze musi byt vetsi nez 0, abych zobrazil jen polozky co jsou skladem, ale hlasi to pri ulozeni: 1. Filter must have value

**Comment by jzelenka** [comment]
je to oboji opravene, ale nasadim to az vecer, ted je to rozvrtane.

Jeste, PRIVATE grid se prirazuje uzivateli, ktery ho vytvari, radkem do tabulky `tco_grid_config_user` , zatim neni GUI na prirazeni PRIVATE gridu dalsim uzivatelum, ale pres insert do DB muzes napriklad vytvorit PRIVATE grid pod sebou a insertem do tco_grid_config_user ho priradit dalsim lidem.

takze muzes napriklad navytvaret ty PENEX gridy jako private pod sebou a pak je pridat dalsim lidem...

**Comment by milant007** [comment]
Ono by pak asi nebylo spatny aby uzivatel tenanta pri volbe public to zobrazil pouze tenantum, ktere ma sam prirazene. ale to ted neni na poradu dne...

**Comment by jzelenka** [comment]
jo jo, udelat to poradne je takove slozitejsi - bude se muset zavest tabulka grid_config_tenant, ktera se naplni temi jeho tenanty  ( = "zobrazil pouze tenantum, ktere ma sam prirazene" )

potom to bude chtit jeste rozlisovat 3 urovne:  private - tenant public - all public
abys nemusel pri pridani tenanta mu prirazovat vsechny gridy.
A aby to nematlo normalni uzivatele uvidi to pouze ten kdo bude mit pravo "PUBLIC GRIDS" ....
takze casem...

Udelej na to nove issue - enhacement, niceToHave.
