### ISSUE TITLE
Fakturace první postřehy

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#44]
Asi sem budu postupně přidávat, ale když na něco narazím, napíšu hned abych nezapomněl:
- při vkládání nové položky se ptá na 3 možnosti. Já bych se určitě neptal, to mi každej uživatel omlátí o hlavu, všichni chtěj klikat co nejméně a přiřadil to podle toho co tam vyplní s tím, že bych zobrazil pole tak aby bylo možný je vyplnit nebo nechat prázdný:

1. 
Item: kdyz uzivatel vypli pouze description, tak je to item. 
2. 
Product: pokud zvolim pouze product a uz nevyberu auto
3. 
Product and vehicle: kdyz zvolim Product i auto.

Akorát vidím problém s cenotvorbou, protože když zadám product, tak se mi dotáhne cena definovaná buď globálně nebo ProductCustomer. A pak vyberu i auto a mělo by to znova juknout do cenotvorby pokud tam náhodou není ProductVehicle.

**Comment by jzelenka** [comment]
Moc se me do toho nechce, je to slozite nacpat to do jednoho formulare. Graficky treba ten product & Vehicle ma potlaceny (kratky) radek description protoze se vyplnuje automaticky z produktu a vehicle. Kdezto u volneho pole je description pres cely radek.

Logika policek je jina - free item nema unit of measure, unit price, mnozstvi.
Vypocet je jinej.
Plus ty ceny jak jsi psal.

To uz bych dal radeji 3 ikonky na bar aby usetrili ten rozklik. Ale jses si jistej ze jim to opravdu bude vadit??

**Comment by jzelenka** [comment]
plus budeme treba casem tu grafiku chtit vymazlit  a to se neda udelat do spolecneho formulare.

**Comment by milant007** [comment]
3 ikonky na bar jsou ok.

**Comment by jzelenka** [comment]
tak si je vyber:
http://fortawesome.github.io/Font-Awesome/icons/

:)

**Comment by milant007** [comment]
ja bych tam nechal ikonu co tam je pro item, pro product bych dal tu samou jako je u productu a u vehicle tu samou jeko je vehicle... :-)

**Comment by jzelenka** [comment]
Muze byt, ale pockejme na prvni stiznosti. Ja porad doufam ze nebudou.

**Comment by milant007** [comment]
Pokracuji v postrehach:

- U vystavení dobropisu, se dotázat ke které FA se dobropis váže. Pokud zakázku založím zkopírováním z původní FA, tak to vím a není třeba se dotazovat. Ale někdy se dělá dobropis ručně a pak při vystavení se musí vybrat FA(od toho samého zákazníka).

- Kopírování položek FA. Pokud zadávám FA ručně, tak např. u Volva zadávám na stejné auto několik různých balíčků, tak abych vše nemusel vyplňovat znovu tak na vybranem radku kliknu kopiruj a otevre se mi nove okno kde bude vse stejne predvyplnene jako na originalu a ja jen upravim auto nebo product nebo trebas jen comment - tak to delam pri fakturaci ja kdyz napr. fakturuji pocitacove komponenty, mam na to product Zbozi ostatni a menim pouze text a cenu, ale chci aby se mi to kvuli statistikam sypalo pod tuto polozku.

**Comment by jzelenka** [comment]
U dobropisu to policko uz je - ale vyhledava mezi vsema fakturama - to opravim
A neni povinne, ma byt?

**Comment by milant007** [comment]
Dal bych ho jako povinné, v Maďarsku povinné je. V CZ zatím ne, ale je dobrý vědět k jaký FA se dobropis váže. Jediný problém může být pokud vystavuji dobropis např. na základě obratu(třebas za předchozí rok) a vracím zpět např. 3% z toho ročního obratu, pak se to váže k vícero FA... Pak nevím zda si prostě bude muset nějakou FA vybrat? Nebo mít zaškrtávadlo že sem si vědom, že vystavovaný dobropis se neváže k žádné konkrétní FA. Ale jde o tom uživatele doutit aby to primárně zadávali. I když většinou budou kopírovat z vystavené FA a tam to nebude třeba...

**Comment by jzelenka** [comment]
dam to ted jako povinne a zaskrtavadlo (ktere to znepovinni) udelame pozdeji az na to nekdo narazi.
Presne podle agilni metody :)

**Comment by milant007** [comment]
souhlas :-)

**Comment by jzelenka** [comment]
oboji hotove.

Zaviram, dalsi veci pis prosim te do dalsich bugu. Ne ze bys nemohl napsat vice veci do jednoho bugu, kdyz na ne prijdes najednou, ale nechci aby vznikal nekonecny bug, ktery pak budu muset zdlouhave procitat....
