### ISSUE TITLE
faktury - otazky k doreseni

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#45]
1. na fakture - v dropdownu pridani polozky bych pridal 4. - Add All Active vehicles - ktere by pridalo vsechny platne produkty pro vsechny auta zakaznika.

2. zkopirovat fakturu a vytvorit dobropis:
 - zkopirovat fakturu ji zkopiruje a vymaze veci ktere se delaji az pri vydanu (cislo faktury, datumy, typ faktury, status bude CONCEPT)
 - vytvorit dobropis - bud se mu to otevre rovnou s otevrenym Issue dialogem (ma smysl pokud dobropis vetsinou nemeni radky) nebo ne a potom se to s vyjimkou otoceni cen/mnozstvi nelisi od "zkopirovat fakturu".

3. musime, asi telefonicky, projit jak budete za duben delat fakturaci - protoze ted uz jde fakturu rucne vydat z GUI a pritom se faktura ulozi do dco_document, din_invoice_document.  Ale pri vasem dosavadnim vydavani ne a asi by se to nemelo lisit - reseni asi bude import skriptem do stavu CONCEPT a pak testem spustena metoda, ktera udela ISSUE .... to abych ale jeste rychle dodelat hromadne stazeni do zipu/spojeneho pdf abyste to pak z db jednodusse dostali....

**Comment by milant007** [comment]
Ad 1. Ano, podle toho jak jsme se bavili i se zohlednenim Profit Centra na hlavicce.
Ad 2. Bude to na dva kroky. Zkopírovat přesně jak píšeš, ale pak si uživatel může zeditovat položky a rozhodnout se, zda bude vystavovat dobropis nebo FA. Já např. u Volva za fuelcheck vystavuji FA tímto způsobem. Je to paušál se zohledněním počtu aut v systému každý měsíc, takže musím upravit a až pak vystavit FA...
Ad 3. viz náš telefonát... Jindra řekne jak generoval PDFka za duben.

**Comment by jzelenka** [comment]
Ad 2.  přesně tak, když dají "zkopírovat" otevře se jim ve stavu CONCEPT - pak s ni můžou dělat co budou chtit.

**Comment by krivohlavek** [comment]
PDFka jsem doteď dělal po staru, ale když jsem to nyní zkusil po novu, tak je to taky OK.

**Comment by jzelenka** [comment]
Dobry, a cetl jsi na https://github.com/zauzoo/app/wiki/Dokumenty
jak je to udelane?

protoze sablona je nyni v DB (pres GUI) a adresar tool/documents se muze smazat.

**Comment by krivohlavek** [comment]
Jo narychlo jsem to prolétl a změny udělal už v db a fungovalo to. Zatím mám jen odzkoušené slovenské faktury a maďarské legal xml (tam ještě doplním ty podmínky z filtru + odkaz na fakturu v případě dobropisu). Zkoušel jsem i variantu přes GUI a test a tam chybí české znaky, ale to už jsi včera psal.

**Comment by jzelenka** [comment]
@krivohlavek 
ceske znaky jsou opravene, 
nasazeno pouze na test.zauzoo.com  (nasazeni do produkce si delejte sami).

**Comment by jzelenka** [comment]
vse tady popsane hotovo:

- 4. polozka v menu: All Vehicles - prida vsechny platne balicky filtrovane podle profitCentera
- Copy Invoice funguje

Navic jsem pridal moznost vytvorit novou fakturu z karty customera (na podgridu invoice). Samozrejme s prednastavenym zakaznikem

Az otestuejte ze jsou tisky OK, dejte vedet, dogenerujeme tisky ke starym fakturam.

**Comment by milant007** [comment]
Ted jsem testoval - pridani vsech platnych balicku:
- pridej pouze ty co jsou naceneny. Chybova hlaska pouze pro pripad kdy to nenajde ani jeden platny balicek. Oni mohou mit prirazeny i balicky, ktery maji ty zakaznici aktivni, ale z nejakeho duvodu se nefakturuji. Takze nemusej skakat do FA. Je tam sice riziko, ze mohou neco zapomenout nacenit, ale s tim jsou srozumneni.

**Comment by jzelenka** [comment]
ok, hotovo.

**Comment by milant007** [comment]
Tak jeste jedna chybka na All vehicles menu.
Nedotahujou se spravne ceny, vsude je unit price 1. Vyzkousel jsem na Lannutti Czech kde je naceneno D00007 Driver Times (Dynafleet), D00005 Positioning (Dynafleet), D00003 Fuel and Environment (Dynafleet) na 15EUR a D00009 Fuelcheck (Dynafleet) 3EUR, ale vsude se dotahla cena 1.

**Comment by jzelenka** [comment]
fixed by #47
