### ISSUE TITLE
Nacenění položek FA

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#47]
Pokud vytvořím položku FA nebo při zadání/změně (ProductItem/ProductVehicle) aby se automaticky dotahla cena. pak ji mohu upravit podle potreb, ale jakmile opet zmenim product/vehicle tak se zase bude dotahovat aktualni cena nastavena v price_component.
Akorat v pripade, ze neexistuje naceneni pro prislusny (ProductItem/ProductVehicle) v price_component se necha v poli unit price to co tam bylo, nemazal bych unit price ani nenuloval.
Testoval jsem na CZ Lannutti auto SPZ 3AR 3370 balíček třebas positioning, kde  by se mělo dotáhnout 15EUR, ale dotáhlo se 1EUR.
Nehori to.

**Comment by jzelenka** [comment]
Opraveno, pushnuto.
