### ISSUE TITLE
Generovani nazvu PDF

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#48]
- Kdyz otevru PDF v prohlizeci, tak aby na horni zalozce bylo invoice_number.
- Kdyz dam stahnout PDF do souboru, tak aby se ukladalo/nabizel nazev jako invoice_number

**Comment by jzelenka** [comment]
pri ulozeni do souboru tam mas: Invoice_ISSUED_97160863.pdf

to se ti nelibi?

**Comment by jzelenka** [comment]
97160863 je invoice_number

**Comment by milant007** [comment]
mne se to nabidlo jako 7.pdf resp. 8.pdf co jsem delal pres gui?

**Comment by jzelenka** [comment]
To si ale ukladal pres ten in-browser pdf. 
Tj. nejdrive kliknul na ikonu PDF, otevrelo se to in-browser a pak ulozit v tom pdf-viewer GUI.

Kdyz kliknes na tu ikonu download.... ??

**Comment by milant007** [comment]
Ok, download dobry.
Tak kdyby se ti to podarilo dostat do nazvu te zalozky v browseru... invoice_number ?

**Comment by jzelenka** [comment]
download z chrome pdf vieweru - vyreseno (nabidne se stejny jako z ikonky download).
horni zalozka - zkuste pridat to pdf metadat polozku `title`  (pri vyrobe metadat)

pokud to nepomuze, tak to nejde.

**Comment by jzelenka** [comment]
zkuste pridat ten title

**Comment by krivohlavek** [comment]
Přidáno v produkci a funguje to.

**Comment by jzelenka** [comment]
good, tak tam dej neco smysluplnyho,
treba Invoice #cisloFaktury

a zavri bug.
(bug by mel zavirat vzdycky ten kdo ho vyresi.)

**Comment by krivohlavek** [comment]
Ok, je tam cislo faktury. Kdyz bude chtit Milan neco jineho, tak to operativne zmenim.
