### ISSUE TITLE
Chyba pri ulozeni FA - polozky

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#49]
Stalo se to kdyz jsem smazal polozku, pak jsem dal novou, a dal ulozit. Takze to vyhnilo na unique key.

Server error 500
PSQLException: ERROR: duplicate key value violates unique constraint "uc_din_invoice_item_01" Detail: Key (invoice_id, item_index)=(7437, 3) already exists.

**Comment by jzelenka** [comment]
opraveno
