### ISSUE TITLE
Polozka FA vc DPH vs bez DPH

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#51]
Behem migrace MultiDaty produkce do ZZ jsem narazil na pripad(Expobank :-) ) kdy jsem cenu za polozku FA nastavil vcetne DPH. V MDckach je zaskrtavadlo, ktere kdyz zaskrtnu tak nemusim brat do ruky kalkulacku a ono to cenu co tam zadam urci uz ze je bez DPH nebo vcetne DPH podle me volby...
Nebylo by to spatny ale da se to kazdopadne vyresit tou kalkulackou.

**Comment by jzelenka** [comment]
Na Free Item polozce jsem otevrel k editaci PriceWithoutVat a ItemPrice (takze jedina zakazana je VatAmount). 

Takze kdyz neco editujes, tak se ostatni dopocita.

u adjustmentKoef & adjustmentAmount jsem si musel vybrat co se zmeni a co zustane - zustane adjustmentKoef a meni se adjustmentAmount (treba kdyz zmenis itemPrice nebo priceWithoutVat).

Tohle je podle me lepsi nez checkbox....

Udelal jsem to zatim jenom u FreeItem - prijde me ze kdyz vybiras produkt tak ho vetsinou mas naceneny. Navic je to dost slozity a u produktu a produkt & vehicle to bude jeste slozitejsi, ale pokud bude nutne udelat to asi lze i u nich.

**Comment by milant007** [comment]
Urcite je to lepsi nez checkbox! Free item staci.
