### ISSUE TITLE
Ciselne rady FA vcetne dobropisu

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#53]
Ted jsem si zadaval ciselnou radu pro MD abych tam vystavil prvni FA pres GUI a doslo mi, ze ja mam pro FA i dobropisy jednu ciselnou radu. ale ty mas pole tin_invoice_number_gen.invoice_type_id ...takze nevyplnovat?

**Comment by jzelenka** [comment]
Jo, invoice_type_id je nepovinne, muzes nevyplnit kdyz nechces rozlisovat. Stejne tak pro profit_center.
Jen tenant je povinny.

Pro predstavu tady je ten select:

      select invoice_number_gen_id from tin_invoice_number_gen" +
        "    where tenant_id = ?" +
        "      and (invoice_type_id = ? or invoice_type_id is null)" +
        "      and (profit_center_id = ? or profit_center_id is null)" +
        "      and (valid_from <= ? OR valid_from IS NULL) AND (valid_to >= ? OR valid_to IS NULL)" +
        "    order by invoice_type_id ASC NULLS LAST, profit_center_id ASC NULLS LAST" +
        "    limit 1

Otevri pokud by to nefungovalo.
