### ISSUE TITLE
vyhledávání billed_to ve fakturaci

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#54]
chtěl jsem zadat FA na spořitelnu do ZZ(tenant 4 = multidata) a nevyhledalo to podle "Čes.." musel jsem začít zadávat "spoř..."

**Comment by milant007** [comment]
tak ještě doplnění, je to asi problém s diakritikou, když dávám "spo..." tak ok, jakmile přidám "spoř.." tak se taky přestane nabízet. nenabídne se ani pro "spor..."

**Comment by jzelenka** [comment]
Opraveno, tak že je to case insensitive, ale accent (háčky, čárky) sensitive.
Tj. stejne jako text search.

pushnuto.

Pokud bychom chtěli accent insensitive, je třeba to udělat na úrovni postgresu (nainstalovat unaccent extension, vytvořit funkční indexy...)  .... což bych rád aby udělali kluci a asi až po upgrade postresql, který je bez výpadku možná jen když koupíme druhý server....

**Comment by milant007** [comment]
s druhym serverem nemam problem, jen bych ho dal geograficky dal od toho prvniho?
