### ISSUE TITLE
tenant group u dpa_party role owner

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#55]
Ted jsem jeste migruji do ZZ toco group(ted to mam hlavne kvuli optimalizaci a majetku). Historicky tam mam ale stejne zakazniky jako v MD. Nastavil jsem tedy tenant group v dpa_party a to funguje jak ma, az me to prekvapilo. :-) Ale ted mam dva ownery v tenant group 1000001. MultiData a toco group a toco jsem si pred tim navic zalozil jako ownera takze ho tam mam jeste 2x. Nevim zda je to nutny oznacovat ownera. Pozname ho i podle toho ze je navazany do tco_tenant, ne ? Ja akorat nevim jak u faktur prirazujes billed_from, na zaklade jake vazby?

**Comment by jzelenka** [comment]
Owneru muze byt vic, je to jen takove oznaceni aby clovek vedel ze ta party je owner a treba ji opatrne editoval. Plus treba kdyz nemas na party customera, ale jen ownera tak vidis zalozky aut. Bez ownera (a bez customera) bys je nevidel.

Party muze mit klidne vice roli:  owner, customer....   pokud to jde (maji stejnou adresu atd) je zadouci tam nemit stejnou osobu vicekrat. Nebo aspon co nejminkrat...

billed_from je z tenanta  (tenant.party)
