### ISSUE TITLE
Hromadna fakturace - prvni pripominky 

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#56]
-	~~Do description dat pouze nazev balicku. Napr.  „Positioning“ místo „D00005 Positioning (Dynafleet) on VOLVO BL155JH“ My to pak na sablone FA podle toho grupujem aby tam bylo Positioning pouze jako jeden radek. Detaily jsou pak vypsane na příloze.~~
-	~~Cena za balicek se všude dotahla 1 EUR~~
-	~~Když vyberu konkretni stredisko napr. Optifleet v prepare, tak asi nepotrebuji videt chybovy hlasky o zakaznicich co mají pouze dynafleet, vyvaruji se tim i chybove hlasky „This customer already has issued invoice for specified invoice period“. Protože pak uz je to neprehledne.~~
-	Do commentu bych rovnou nabizel text v prislusnem jazyku napr SK:  Fakturujeme Vám <PROFIT_CENTER_NAME>  za obdobie od <DATE_FROM>  do < DATE_TO> V zavorkach by se dynamicky doplnily texty.
-	~~Generovani PREPARE sekce pro 33  faktur trva 20 vterin…~~
-	~~ISSUE 33 faktur se pak generovalo 2,5 minuty, nevim zda to linearne stoupa s poctem faktur, ale v cechach se bude vystavovat 500 faktur, to by znamenalo cca pul hodiny?~~
-	~~Zakaznici co mají i optifleet i dynafleet musí mit faktury oddelene i když bych to dal generovat všechno v jednom bez ohledu na stredisko. V SK napr 3106, 3107. Jedna FA musí byt na dynafleet s logem Volva druha na optifleet s logem Renault. Pokud to dam generovat oddelene, tak mi to hlasi, ze uz na nej FA byla vystavena, takze kontrolovat v ramci střediska.~~

**Comment by jzelenka** [comment]
skrtnute je hotove.

**Comment by milant007** [comment]
jen pro info ted jsem otestoval: 192 faktur se generuje 18 minut

**Comment by krivohlavek** [comment]
Nevím jak to máš Honzo dělané na pozadí, ale neušetřil by se nějaký čas kdyby bylo jedno velké xml ze všech faktur? Test vždycky tahal jednu fakturu/xml za druhou a díky tomu to bylo pomalejší - šablonu bych upravil kdyby to mělo pozitivní vliv na čas.

**Comment by jzelenka** [comment]
tohle by bylo neprijemne - pak se to muselo delit. Divam se jak to zrcyhlit bez spojovani.

**Comment by jzelenka** [comment]
Melo by to byt vsechno opravene krome:

> Do commentu bych rovnou nabizel text v prislusnem jazyku napr SK: Fakturujeme Vám za obdobie ?> od do < DATE_TO> V zavorkach by se dynamicky doplnily texty.

Coz me prijde trochu nedospecifikovane.

Vybrane faktury, respektive customeri, muzou mit vice nez jeden jazyk. Takze by tam zrejme mel byt tab se vsemi jazyky, ktere se vyskytuji na vybranych customerech.

Dale by ten text mel byt asi konfigurovan podle tenanta ne?

Takze konfiguracni tabulka kde bude per tenant a jazyk a per nejaky ucel (tady invoiceComment) nastaven defaultni comment. 
?

**Comment by milant007** [comment]
Ano, konfiguracni tabulka per tenant a jazyk, ale tohle urcite nehori.

**Comment by milant007** [comment]
hele tak ty commenty my ted vyresime pres sablonu FA, Jindra to upravi. A resil bych to, pokud ten dotaz vyvstane jeste od nekoho dalsiho.

**Comment by jzelenka** [comment]
Tim myslis ze date do sablony neco natvrdo a invoice.comment se nepouzije?

**Comment by milant007** [comment]
Ano, pokud je vyplnen start a end time period, tak zobrazime vetu v prislusnem jazyce ktera je natvrdo v sablone. A comment si pripadne vyplnej cim budou chtit, ten se bude na FA zobrazovat take pokud bude vyplnen.

**Comment by jzelenka** [comment]
ok
