### ISSUE TITLE
chyba pri nastaveni MultiData role jako customer

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#57]
Kdyz chci u MultiData nastavit roli customer v tenantovi 6(toco) tak to vyhodi chybovou hlasku nize. Urcite to bude tim, ze jsme pouzil pro tenanty 4 a 6 tenant group 1000001 v dpa_party. Mozna jsem jeste nekde neco blbe updatnul v datech, ale nevim kde a co:

Client Error
e/this.prunedGridArray<@http://zauzoo.com/module-33c6a6ed.js:1:6793 e@http://zauzoo.com/module-33c6a6ed.js:1:6772 s@http://zauzoo.com/module-33c6a6ed.js:40:11809 u/</r</s.prototype.computeStateProps@http://zauzoo.com/module-33c6a6ed.js:54:21309 u/</r</s.prototype.updateStatePropsIfNeeded@http://zauzoo.com/module-33c6a6ed.js:54:22148 l@http://zauzoo.com/module-33c6a6ed.js:54:20236 u/</r</s.prototype.handleChange@http://zauzoo.com/module-33c6a6ed.js:54:23760 c@http://zauzoo.com/module-33c6a6ed.js:32:6456 n/</<@http://zauzoo.com/module-33c6a6ed.js:59:12176 n/<@http://zauzoo.com/module-33c6a6ed.js:59:12897 l/n</<.value/s</v.onBlur@http://zauzoo.com/module-33c6a6ed.js:1:30789 t/n.onBlurEvent@http://zauzoo.com/module-33c6a6ed.js:2:8959 Zauzoo.module</C<.handleInputBlur@http://zauzoo.com/module-33c6a6ed.js:30:21921 r@http://zauzoo.com/module-33c6a6ed.js:31:29549 a@http://zauzoo.com/module-33c6a6ed.js:31:16129 s@http://zauzoo.com/module-33c6a6ed.js:31:16342 Zauzoo.module</d@http://zauzoo.com/module-33c6a6ed.js:10:12475 Zauzoo.module</p@http://zauzoo.com/module-33c6a6ed.js:10:12603 Zauzoo.module</n@http://zauzoo.com/module-33c6a6ed.js:32:4845 Zauzoo.module</m.processEventQueue@http://zauzoo.com/module-33c6a6ed.js:10:13723 r@http://zauzoo.com/module-33c6a6ed.js:58:11929 Zauzoo.module</i.handleTopLevel@http://zauzoo.com/module-33c6a6ed.js:58:12037 a@http://zauzoo.com/module-33c6a6ed.js:58:12484 i@http://zauzoo.com/module-33c6a6ed.js:58:12300 Zauzoo.module</o.perform@http://zauzoo.com/module-33c6a6ed.js:12:17393 Zauzoo.module</f.batchedUpdates@http://zauzoo.com/module-33c6a6ed.js:31:25632 i@http://zauzoo.com/module-33c6a6ed.js:6:1624 Zauzoo.module</y.dispatchEvent@http://zauzoo.com/module-33c6a6ed.js:58:13376

**Comment by jzelenka** [comment]
nesouviselo to s tenanty, tenantgroupy ani toco, ale jen s tim ze pri pridani role customera na existujici party se dynamicky pridaji nove subgridy. 
Coz prestalo fungovat zrejme po nejake me jine zmene..

pushnuto.
