### ISSUE TITLE
Rumunsko pozadavky

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#58]
- Hromadna fakturace v Rumunsku probiha tak, ze nekteri zakaznici se fakturuji v aktualnim mesici tak jak to ted probihe vsude. Ale cca 20% zakazniku se fakturuje zpetne. Ja bych to resil tak, ze bude by mohl byt parametr/pole s informaci zpetna Fakturace. Pak by se zalozil grid Fakturace aktualni kde by se vyfiltrovali pouze zakaznici co maji aktualni fakturaci. A pak grid Fakturace zpetne a vyfiltrovali se ty se zpetnou. Nad obojim by se postupne spustila hromadna fakturace, a tam by se podle me ani nemuselo nic menit, obdobi si tam muzes vybrat uz ted...
- Rumunske Volvo nepouziva denni kurz ale mesicni. Vzdy 10. vezmou kurz z "RNB" a ten drzej cely mesic. My muzem samozrejme stahovat denni kurz tak jako v CZ a HU, ale tenant Volvo RO si bude kurz menit manualne.

**Comment by jzelenka** [comment]
ad 1)  tedy moje upravy:  pridat nekam na customera priznak "fakturace zpetne"

ad 2) muzeme to zautomatizovat, pokud pridame download RNB kurzu (sezente me link) a naschedulujeme ho jenom na 10.  Uz ted mame na tenantovi preferedRateSource kam dame rumunsku "RNB" aby se bral kurz RON/EUR z RNB. Pak to stejne samozrejme budou moct prepsat jako ostatni...

**Comment by jzelenka** [comment]
do kdy tohle ma deadline? tenhle tyden uz moc nebudu.

**Comment by milant007** [comment]
cca mesic

**Comment by milant007** [comment]
Ad1) priznak ano, ale asi bych z duvodu uspory mista nejake informace daval na novou zalozku nebo nevim kam, aby nam vsechny tyto doplnujici informace nevytlacily v Party zalozky Invoice, InvoiceDetails, Relationsships dolu ven z obrazovky. To se muze tykat i volby Volvo Logins, Accounting Matching ID atd. Ze zkusenosti vim, ze nejvic se na kartu zakaznika leze aby jsi co nejrychleji vyfiltroval neco v zalozce InvoiceDetails. A cim Bude niz, tim min toho bude videt.

Ad2) Rumuni si chtej kurz zadavat rucne. Oni si za posledni mesic vyberou pro ne nejvyhodneji kurz z RNB a ten si nahodej pro dalsi mesic. :-) Takze link jsem poptal, abychom stahovali kurzy, ale VOLVO RO to pouzivat nebude.

**Comment by milant007** [comment]
Hele zatim bod 1 neres, nez nam to vybehne z obrazovky, tak to jeste chvili potrva a ted zkoumam to  https://github.com/zauzoo/app/issues/34#issuecomment-220784269 jak funguje a to nam defakto bod 1 resi.

**Comment by jzelenka** [comment]
bod 2 vyresen v ramci bugu #69, zaviram.
