### ISSUE TITLE
Chybějící elementy v XML

### ISSUE THREAD

**Issue by krivohlavek** [zauzoo/app#59]
Do XML Object bych potřeboval:
1) fromFax - chybí v xml. V db sloupec je a je správně vyplněn i při hromadné fakturaci.
2) parma - je to účetní párovací znak, každý zákazník bude mít trošku jiné pojmenování, ale bude u všech. Dříve jsem ho načítal z  /billedTo/contacts/contactType[name='parma'], bohužel contacts v xml už nejsou.
3) fromIban - špatně naplněno hromadnou fakturací (aktuálně je stejné jako fromIbanLcy, ale má být jiné)

**Comment by krivohlavek** [comment]
Ještě jak je v <party> uveden kdo vystavil fakturu, tak bych potřeboval vytahovat i email k této osobě. Na faktuře je kromě jména i email (zatím ho mám natvrdo v kódu).

Je tam ještě razítko s podpisem (vkládáno png), ale zatím nevznikl požadavek na různá razítka. Když by se mělo dělat extra pole pro mail, tak kdyžtak počítat s něčím univerzálním - někdo může chtít uvádět třeba telefon atd.

**Comment by jzelenka** [comment]
> 1) fromFax

podle me je to dobre.

```XML
<fromFullName>Volvo Hungária Kft</fromFullName>
<fromIco>12345679</fromIco>
<fromDic>HU11841674</fromDic>
<fromIcoDph>11841674-2-44</fromIcoDph>
<fromPhone>+36 1 253 0880</fromPhone>
<fromFax>+36 1 253 0899</fromFax>
<fromEmail>finance.hu@volvo.com</fromEmail>
<fromUrl>www.volvotrucks.hu</fromUrl>
<toFullName>Erika-Euro Transsped Kft</toFullName>
```

> 2) parma

pridal jsem na fakturu policko `accountingMatchingId`, zatim se neplni, ale muzes predelat sablonu aby ho brala. Jeste na to napisu, bude to soucast reseni #34 

> 3) fromIban 

podle me je to dobre.

**Priste prosim uvadej prostredi (dev/test/prod) a invoiceId kde jsi chybu objevil**

**Comment by jzelenka** [comment]
U roli osob na fakture (vystavil, objednal) jsem zatim neudelal kopirovani policek z party na fakturu. Takze to ted napravuju.

Takze kde bylo drive (a chybel telefon) : 

```XML
<roles>
	<roleType>
		<invoiceRoleTypeId>2</invoiceRoleTypeId>
		<name>Ordered by</name>
	</roleType>
	<party>
		<partyId>3572</partyId>
		<fullName>Molnár Károly Ferencné</fullName>
		<firstName>Molnár</firstName>
		<lastName>Károly Ferencné</lastName>
		<partyCategory>FO</partyCategory>
		<active>false</active>
	</party>
</roles>
<roles>
	<roleType>
		<invoiceRoleTypeId>1</invoiceRoleTypeId>
		<name>Issued by</name>
	</roleType>
	<party>
		<partyId>100000</partyId>
		<fullName>Jan Zelenka</fullName>
		<firstName>Jan</firstName>
		<lastName>Zelenka</lastName>
		<partyCategory>FO</partyCategory>
		<active>false</active>
	</party>
</roles>
````

tak ted je:

```XML
<roles>
	<roleType>
		<invoiceRoleTypeId>2</invoiceRoleTypeId>
		<name>Ordered by</name>
	</roleType>
	<party>3572</party>
	<phone/>
	<fullName>Molnár Károly Ferencné</fullName>
	<email/>
</roles>
<roles>
	<roleType>
		<invoiceRoleTypeId>1</invoiceRoleTypeId>
		<name>Issued by</name>
	</roleType>
	<party>100000</party>
	<phone/>
	<fullName>Jan Zelenka</fullName>
	<email/>
</roles>
```

Vsimni si ze party uz je jenom idecko - to je schvalne a je to i na billedFrom/To. Protoze z party by se nic brat nemelo, vsechno by melo byt prekopirovane na invoice.

**Comment by jzelenka** [comment]
Pokud budete chtit opravit existujici faktury, tak full_name, phone, email jsou pridane na d_invoice_role.

**Comment by jzelenka** [comment]
Takze uz je udelane plneni accountingMatchingId z PartyFeature, jak popsano v #34.
Tj. na novych fakturach, pokud ma party billedTo vyplnene toto feature, se accountingMatchingId vyplni.

**Comment by krivohlavek** [comment]
Dik,
