### ISSUE TITLE
grid testing

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#6]
Na zauzoo jsou udelane gridy (jako polozky v menu) pro zakazniky, kontakty a sales reps.
Kazda stranka ma jen jeden grid, policka jsem dal vicemene stejna jako v MD, v toolmenu je polozka Manage (ve vyberu gridu) kde se da grid upravovat, nadefinovat dalsi nebo mazat. Administrace gridu jeste neni uplne hotove (validace, blbovzdornost, grafika), to dodelam spolu s formularem Party, ale je funkcni.

Ted vidim ze policka jsou sirsi nez je nutne, to delal martin, zadam mu to.

**Comment by jzelenka** [comment]
Je asi chyba v partyRoles - parties s roli typu salesRep (id 3) je jen 34, ale PartyRel s typem relace salesRep (Id 2) je hodne.

Ja party pro jednotlive gridy omezuju prave podle toho ze ma roli.

**Comment by milant007** [comment]
Zatim jsem nasel toto(testovano v Mozille):
- u show selection(zobrazim vyber radku) kdyz dam oznacit vse a pak vse ododznacit, tak to nic neudela, nefunguje u Customers, ALE contact persons a sales representative to funguje! nema na grid byt pouze jedna funkcionalita?
- pokud najedu mysi na "show selection" nebo "refresh" tak se infotext zobrazi do nadpisu gridu a stejne nejde precist o co se jedna - ale to je nepodstatna banalita
- v poli search vyhledavat asi pres vsechny sloupce kde je varchar - pokud to zauzoo nejak nezpomali? urcite budou chtit vyhledavat podle ulice ic dic, mista, emailu atd.
- pri Manage vytvoreni vlastniho gridu to nekdy nejde ulozit a to bez chybove hlasky nebo s "Server error 500 java.lang.NullPointerException" prijde mi to kdyz jsem zvolil i filtr(jakykoliv), bez filtru to fungovalo. 
- vlastni grid - customers, "TEST PRAHA", po zvoleni hodil tuto chybu: Server error 500 org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'String' is defined
- vlastni grid - Sales Representatives, "test" vraci 2361 radku presto ze obchodaku je 34
- BACHA to smrdí, jeden z obchodaku Volva se jmenuje Bureš!!!!!!! :-)
- ty filtry pro kazdy column extra asi jeste nefunguji?
- pri setrideni v gridu podle poli co se tahaji z jine tabulky nez PARTY, napr adresa, kontaktni udaje, atd. to hazi tuto chybu: Server error 500 org.hibernate.QueryException: could not resolve property: addresses_PERMANENT of: com.zauzoo.party.domain.Party
- asi byla kravina to zkouset, ale kdyz jsem dal jiny jazyk nez cs, tak uz jsem si ani nesrtnul s chybovou hlaskou: Server error 500 org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'undefined' is defined. A i kdyz jsem pak vratil cs a refreshoval nekolikrat prohlizec a zkusil pak i v chrome, tak nic. Takze ted neni co dal testovat. :-(

**Comment by jzelenka** [comment]
je to nasazene, viz vyse.

**Comment by jzelenka** [comment]
Na grid Party / Contacts pridano policko Customer Full Name.

Jeste prece jenom, kdybyste s Martinem ladili ty policka co se ucastni searche, tak at radeji udela pro finalni nastaveni pull request (misto primeho commitu), ona je konfigurace tech poli z navazanych entit docela slozita (hlavne tyhle pres vazbu, protoze to je pres dpa_party_rel zpatky do dpa_party...)

**Comment by jzelenka** [comment]
pridal jsem vyhledavani podle partyId - na EQUAL, tj. lze i podle ciselnych polozek.

**Comment by milant007** [comment]
- nevim zda je to chyba nebo ne, pro jistotu to pisu. kdyz v show selections vyberu konkretni zaznamy, tak pote pri setrideni dle jakehokoliv sloupce to vybrane zaznamy zapomene.
- vytvoril jsem nad customers grid TEST01 a ten nefunguje: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
- asi k zamysleni na vlastni issue moznost do gridu napsat where, kdyz budu chtit vybirat zaznamy slozitejsim zpusobem

**Comment by jzelenka** [comment]
ztrata selections pri pretrideni - to je asi featura, snad to nevadi, alespon zatim.

TEST01 - opraveno

vlastni where - nevim - prikladam select ktery to udela z TEST01 ....

            SELECT _first_custcont_party.party_id as party_id1_14_13_, _first_custcont_party.date_created as date_cre2_14_13_, _first_custcont_party.date_updated as date_upd3_14_13_, _first_custcont_party.user_created as user_cre4_14_13_, _first_custcont_party.user_updated as user_upd5_14_13_, _first_custcont_party.tenant_id as tenant_i6_14_13_, _first_custcont_party.active as active7_14_13_, _first_custcont_party.birth_last_name as birth_la8_14_13_, _first_custcont_party.birth_number as birth_nu9_14_13_, _first_custcont_party.date_of_birth as date_of10_14_13_, _first_custcont_party.default_currency as default22_14_13_, _first_custcont_party.default_lang as default23_14_13_, _first_custcont_party.default_payment_cond_id as default24_14_13_, _first_custcont_party.dic as dic11_14_13_, _first_custcont_party.first_name as first_n12_14_13_, _first_custcont_party.full_name as full_na13_14_13_, _first_custcont_party.gender as gender14_14_13_, _first_custcont_party.ico as ico15_14_13_, _first_custcont_party.last_name as last_na16_14_13_, _first_custcont_party.legal_form_id as legal_f25_14_13_, _first_custcont_party.marketing_source_id as marketi26_14_13_, _first_custcont_party.nace_code_id as nace_co27_14_13_, _first_custcont_party.nationality as nationa28_14_13_, _first_custcont_party.owner_id as owner_i29_14_13_, _first_custcont_party.party_category as party_c17_14_13_, _first_custcont_party.place_of_birth as place_o18_14_13_, _first_custcont_party.salutation as salutat19_14_13_, _first_custcont_party.tax_domicile as tax_dom30_14_13_, _first_custcont_party.title_after as title_a20_14_13_, _first_custcont_party.title_before as title_b21_14_13_, _contacts_MOBIL.party_id as party_i13_15_4__, _contacts_MOBIL.party_contact_id as party_co1_15_4__, _contacts_MOBIL.party_contact_id as party_co1_15_16_, _contacts_MOBIL.date_created as date_cre2_15_16_, _contacts_MOBIL.date_updated as date_upd3_15_16_, _contacts_MOBIL.user_created as user_cre4_15_16_, _contacts_MOBIL.user_updated as user_upd5_15_16_, _contacts_MOBIL.tenant_id as tenant_i6_15_16_, _contacts_MOBIL.comment as comment7_15_16_, _contacts_MOBIL.contact_type_id as contact12_15_16_, _contacts_MOBIL.order_by_type as order_by8_15_16_, _contacts_MOBIL.party_id as party_i13_15_16_, _contacts_MOBIL.valid_from as valid_fr9_15_16_, _contacts_MOBIL.valid_to as valid_t10_15_16_, _contacts_MOBIL.value as value11_15_16_, _owner.username as username1_33_1_, _owner.date_created as date_cre2_33_1_, _owner.date_updated as date_upd3_33_1_, _owner.user_created as user_cre4_33_1_, _owner.user_updated as user_upd5_33_1_, _owner.tenant_id as tenant_i6_33_1_, _owner.credentials_expired as credenti7_33_1_, _owner.dashboard_id as dashboa21_33_1_, _owner.email as email8_33_1_, _owner.enabled as enabled9_33_1_, _owner.expired as expired10_33_1_, _owner.first_name as first_n11_33_1_, _owner.hr_number as hr_numb12_33_1_, _owner.internal_line as interna13_33_1_, _owner.last_name as last_na14_33_1_, _owner.locked as locked15_33_1_, _owner.mobile as mobile16_33_1_, _owner.password as passwor17_33_1_, _owner.position as positio18_33_1_, _owner.title_after as title_a19_33_1_, _owner.title_before as title_b20_33_1_, _first_custcont_party_rel.from_party_id as from_pa13_19_1__, _first_custcont_party_rel.party_rel_id as party_re1_19_1__, _first_custcont_party_rel.party_rel_id as party_re1_19_11_, _first_custcont_party_rel.date_created as date_cre2_19_11_, _first_custcont_party_rel.date_updated as date_upd3_19_11_, _first_custcont_party_rel.user_created as user_cre4_19_11_, _first_custcont_party_rel.user_updated as user_upd5_19_11_, _first_custcont_party_rel.tenant_id as tenant_i6_19_11_, _first_custcont_party_rel.comments as comments7_19_11_, _first_custcont_party_rel.description as descript8_19_11_, _first_custcont_party_rel.from_party_id as from_pa13_19_11_, _first_custcont_party_rel.from_party_order_by_type as from_par9_19_11_, _first_custcont_party_rel.party_rel_type_id as party_r14_19_11_, _first_custcont_party_rel.to_party_id as to_part15_19_11_, _first_custcont_party_rel.to_party_order_by_type as to_part10_19_11_, _first_custcont_party_rel.valid_from as valid_f11_19_11_, _first_custcont_party_rel.valid_to as valid_t12_19_11_, _nationality.iso_code_alpha as iso_code1_1_5_, _nationality.date_created as date_cre2_1_5_, _nationality.date_updated as date_upd3_1_5_, _nationality.user_created as user_cre4_1_5_, _nationality.user_updated as user_upd5_1_5_, _nationality.tenant_id as tenant_i6_1_5_, _nationality.iso_code_alpha3 as iso_code7_1_5_, _nationality.iso_code_numeric as iso_code8_1_5_, _nationality.name as name9_1_5_, _addresses_pernament.party_id as party_i19_13_0__, _addresses_pernament.address_id as address_1_13_0__, _addresses_pernament.address_id as address_1_13_10_, _addresses_pernament.date_created as date_cre2_13_10_, _addresses_pernament.date_updated as date_upd3_13_10_, _addresses_pernament.user_created as user_cre4_13_10_, _addresses_pernament.user_updated as user_upd5_13_10_, _addresses_pernament.tenant_id as tenant_i6_13_10_, _addresses_pernament.address_parser as address_7_13_10_, _addresses_pernament.address_type as address_8_13_10_, _addresses_pernament.adresa_kod as adresa_k9_13_10_, _addresses_pernament.city as city10_13_10_, _addresses_pernament.comment as comment11_13_10_, _addresses_pernament.country_id as country18_13_10_, _addresses_pernament.descriptive_number as descrip12_13_10_, _addresses_pernament.name as name13_13_10_, _addresses_pernament.orientational_number as orienta14_13_10_, _addresses_pernament.party_id as party_i19_13_10_, _addresses_pernament.street as street15_13_10_, _addresses_pernament.to_hands as to_hand16_13_10_, _addresses_pernament.zip as zip17_13_10_, _legal_form.legal_form_id as legal_fo1_4_8_, _legal_form.date_created as date_cre2_4_8_, _legal_form.date_updated as date_upd3_4_8_, _legal_form.user_created as user_cre4_4_8_, _legal_form.user_updated as user_upd5_4_8_, _legal_form.tenant_id as tenant_i6_4_8_, _legal_form.name as name7_4_8_, _contacts_EMAIL.party_id as party_i13_15_2__, _contacts_EMAIL.party_contact_id as party_co1_15_2__, _contacts_EMAIL.party_contact_id as party_co1_15_14_, _contacts_EMAIL.date_created as date_cre2_15_14_, _contacts_EMAIL.date_updated as date_upd3_15_14_, _contacts_EMAIL.user_created as user_cre4_15_14_, _contacts_EMAIL.user_updated as user_upd5_15_14_, _contacts_EMAIL.tenant_id as tenant_i6_15_14_, _contacts_EMAIL.comment as comment7_15_14_, _contacts_EMAIL.contact_type_id as contact12_15_14_, _contacts_EMAIL.order_by_type as order_by8_15_14_, _contacts_EMAIL.party_id as party_i13_15_14_, _contacts_EMAIL.valid_from as valid_fr9_15_14_, _contacts_EMAIL.valid_to as valid_t10_15_14_, _contacts_EMAIL.value as value11_15_14_, _first_sr_party_rel_type.party_rel_type_id as party_re1_10_18_, _first_sr_party_rel_type.date_created as date_cre2_10_18_, _first_sr_party_rel_type.date_updated as date_upd3_10_18_, _first_sr_party_rel_type.user_created as user_cre4_10_18_, _first_sr_party_rel_type.user_updated as user_upd5_10_18_, _first_sr_party_rel_type.tenant_id as tenant_i6_10_18_, _first_sr_party_rel_type.name as name7_10_18_, _first_sr_party_rel_type.valid_from as valid_fr8_10_18_, _first_sr_party_rel_type.valid_to as valid_to9_10_18_, _tax_domicile.iso_code_alpha as iso_code1_1_4_, _tax_domicile.date_created as date_cre2_1_4_, _tax_domicile.date_updated as date_upd3_1_4_, _tax_domicile.user_created as user_cre4_1_4_, _tax_domicile.user_updated as user_upd5_1_4_, _tax_domicile.tenant_id as tenant_i6_1_4_, _tax_domicile.iso_code_alpha3 as iso_code7_1_4_, _tax_domicile.iso_code_numeric as iso_code8_1_4_, _tax_domicile.name as name9_1_4_, _first_sr_party_rel.to_party_id as to_part15_19_5__, _first_sr_party_rel.party_rel_id as party_re1_19_5__, _first_sr_party_rel.party_rel_id as party_re1_19_17_, _first_sr_party_rel.date_created as date_cre2_19_17_, _first_sr_party_rel.date_updated as date_upd3_19_17_, _first_sr_party_rel.user_created as user_cre4_19_17_, _first_sr_party_rel.user_updated as user_upd5_19_17_, _first_sr_party_rel.tenant_id as tenant_i6_19_17_, _first_sr_party_rel.comments as comments7_19_17_, _first_sr_party_rel.description as descript8_19_17_, _first_sr_party_rel.from_party_id as from_pa13_19_17_, _first_sr_party_rel.from_party_order_by_type as from_par9_19_17_, _first_sr_party_rel.party_rel_type_id as party_r14_19_17_, _first_sr_party_rel.to_party_id as to_part15_19_17_, _first_sr_party_rel.to_party_order_by_type as to_part10_19_17_, _first_sr_party_rel.valid_from as valid_f11_19_17_, _first_sr_party_rel.valid_to as valid_t12_19_17_, _party.party_id as party_id1_14_0_, _party.date_created as date_cre2_14_0_, _party.date_updated as date_upd3_14_0_, _party.user_created as user_cre4_14_0_, _party.user_updated as user_upd5_14_0_, _party.tenant_id as tenant_i6_14_0_, _party.active as active7_14_0_, _party.birth_last_name as birth_la8_14_0_, _party.birth_number as birth_nu9_14_0_, _party.date_of_birth as date_of10_14_0_, _party.default_currency as default22_14_0_, _party.default_lang as default23_14_0_, _party.default_payment_cond_id as default24_14_0_, _party.dic as dic11_14_0_, _party.first_name as first_n12_14_0_, _party.full_name as full_na13_14_0_, _party.gender as gender14_14_0_, _party.ico as ico15_14_0_, _party.last_name as last_na16_14_0_, _party.legal_form_id as legal_f25_14_0_, _party.marketing_source_id as marketi26_14_0_, _party.nace_code_id as nace_co27_14_0_, _party.nationality as nationa28_14_0_, _party.owner_id as owner_i29_14_0_, _party.party_category as party_c17_14_0_, _party.place_of_birth as place_o18_14_0_, _party.salutation as salutat19_14_0_, _party.tax_domicile as tax_dom30_14_0_, _party.title_after as title_a20_14_0_, _party.title_before as title_b21_14_0_, _default_currency.iso_code_alpha as iso_code1_2_6_, _default_currency.date_created as date_cre2_2_6_, _default_currency.date_updated as date_upd3_2_6_, _default_currency.user_created as user_cre4_2_6_, _default_currency.user_updated as user_upd5_2_6_, _default_currency.tenant_id as tenant_i6_2_6_, _default_currency.currency_name as currency7_2_6_, _default_currency.decimal_places as decimal_8_2_6_, _default_currency.iso_code_numeric as iso_code9_2_6_, _marketing_source.marketing_source_id as marketin1_5_9_, _marketing_source.date_created as date_cre2_5_9_, _marketing_source.date_updated as date_upd3_5_9_, _marketing_source.user_created as user_cre4_5_9_, _marketing_source.user_updated as user_upd5_5_9_, _marketing_source.tenant_id as tenant_i6_5_9_, _marketing_source.name as name7_5_9_, _default_language.lang as lang1_3_2_, _default_language.date_created as date_cre2_3_2_, _default_language.date_updated as date_upd3_3_2_, _default_language.user_created as user_cre4_3_2_, _default_language.user_updated as user_upd5_3_2_, _default_language.tenant_id as tenant_i6_3_2_, _default_language.name as name7_3_2_, _first_custcont_party_rel_type.party_rel_type_id as party_re1_10_12_, _first_custcont_party_rel_type.date_created as date_cre2_10_12_, _first_custcont_party_rel_type.date_updated as date_upd3_10_12_, _first_custcont_party_rel_type.user_created as user_cre4_10_12_, _first_custcont_party_rel_type.user_updated as user_upd5_10_12_, _first_custcont_party_rel_type.tenant_id as tenant_i6_10_12_, _first_custcont_party_rel_type.name as name7_10_12_, _first_custcont_party_rel_type.valid_from as valid_fr8_10_12_, _first_custcont_party_rel_type.valid_to as valid_to9_10_12_, _first_sr_party.party_id as party_id1_14_19_, _first_sr_party.date_created as date_cre2_14_19_, _first_sr_party.date_updated as date_upd3_14_19_, _first_sr_party.user_created as user_cre4_14_19_, _first_sr_party.user_updated as user_upd5_14_19_, _first_sr_party.tenant_id as tenant_i6_14_19_, _first_sr_party.active as active7_14_19_, _first_sr_party.birth_last_name as birth_la8_14_19_, _first_sr_party.birth_number as birth_nu9_14_19_, _first_sr_party.date_of_birth as date_of10_14_19_, _first_sr_party.default_currency as default22_14_19_, _first_sr_party.default_lang as default23_14_19_, _first_sr_party.default_payment_cond_id as default24_14_19_, _first_sr_party.dic as dic11_14_19_, _first_sr_party.first_name as first_n12_14_19_, _first_sr_party.full_name as full_na13_14_19_, _first_sr_party.gender as gender14_14_19_, _first_sr_party.ico as ico15_14_19_, _first_sr_party.last_name as last_na16_14_19_, _first_sr_party.legal_form_id as legal_f25_14_19_, _first_sr_party.marketing_source_id as marketi26_14_19_, _first_sr_party.nace_code_id as nace_co27_14_19_, _first_sr_party.nationality as nationa28_14_19_, _first_sr_party.owner_id as owner_i29_14_19_, _first_sr_party.party_category as party_c17_14_19_, _first_sr_party.place_of_birth as place_o18_14_19_, _first_sr_party.salutation as salutat19_14_19_, _first_sr_party.tax_domicile as tax_dom30_14_19_, _first_sr_party.title_after as title_a20_14_19_, _first_sr_party.title_before as title_b21_14_19_, _default_payment_cond.payment_cond_id as payment_1_0_7_, _default_payment_cond.date_created as date_cre2_0_7_, _default_payment_cond.date_updated as date_upd3_0_7_, _default_payment_cond.user_created as user_cre4_0_7_, _default_payment_cond.user_updated as user_upd5_0_7_, _default_payment_cond.tenant_id as tenant_i6_0_7_, _default_payment_cond.due_date_days as due_date7_0_7_, _default_payment_cond.name as name8_0_7_, _contacts_PHONE.party_id as party_i13_15_3__, _contacts_PHONE.party_contact_id as party_co1_15_3__, _contacts_PHONE.party_contact_id as party_co1_15_15_, _contacts_PHONE.date_created as date_cre2_15_15_, _contacts_PHONE.date_updated as date_upd3_15_15_, _contacts_PHONE.user_created as user_cre4_15_15_, _contacts_PHONE.user_updated as user_upd5_15_15_, _contacts_PHONE.tenant_id as tenant_i6_15_15_, _contacts_PHONE.comment as comment7_15_15_, _contacts_PHONE.contact_type_id as contact12_15_15_, _contacts_PHONE.order_by_type as order_by8_15_15_, _contacts_PHONE.party_id as party_i13_15_15_, _contacts_PHONE.valid_from as valid_fr9_15_15_, _contacts_PHONE.valid_to as valid_t10_15_15_, _contacts_PHONE.value as value11_15_15_, _nace_code.nace_code_id as nace_cod1_6_3_, _nace_code.date_created as date_cre2_6_3_, _nace_code.date_updated as date_upd3_6_3_, _nace_code.user_created as user_cre4_6_3_, _nace_code.user_updated as user_upd5_6_3_, _nace_code.tenant_id as tenant_i6_6_3_, _nace_code.name as name7_6_3_ FROM dpa_party _party LEFT OUTER JOIN tco_user _owner ON _party.owner_id = _owner.username LEFT OUTER JOIN cpa_language _default_language ON _party.default_lang = _default_language.lang LEFT OUTER JOIN cpa_nace_code _nace_code ON _party.nace_code_id = _nace_code.nace_code_id LEFT OUTER JOIN cpa_country _tax_domicile ON _party.tax_domicile = _tax_domicile.iso_code_alpha LEFT OUTER JOIN cpa_country _nationality ON _party.nationality = _nationality.iso_code_alpha LEFT OUTER JOIN cpa_currency _default_currency ON _party.default_currency = _default_currency.iso_code_alpha LEFT OUTER JOIN cin_payment_cond _default_payment_cond ON _party.default_payment_cond_id = _default_payment_cond.payment_cond_id LEFT OUTER JOIN cpa_legal_form _legal_form ON _party.legal_form_id = _legal_form.legal_form_id LEFT OUTER JOIN cpa_marketing_source _marketing_source ON _party.marketing_source_id = _marketing_source.marketing_source_id left outer join dpa_address _addresses_pernament on _party.party_id = _addresses_pernament.party_id and _addresses_pernament.address_type = 'PERMANENT'  left outer join (dpa_party_rel _first_custcont_party_rel join dpa_party _first_custcont_party on _first_custcont_party_rel.to_party_id = _first_custcont_party.party_id) on _party.party_id = _first_custcont_party_rel.from_party_id and _first_custcont_party_rel.party_rel_type_id = 1 and _first_custcont_party_rel.from_party_order_by_type = 1 left outer join cpa_party_rel_type _first_custcont_party_rel_type on _first_custcont_party_rel.party_rel_type_id = _first_custcont_party_rel_type.party_rel_type_id   left outer join dpa_party_contact _contacts_EMAIL on _party.party_id = _contacts_EMAIL.party_id and _contacts_EMAIL.order_by_type = 1 and _contacts_EMAIL.contact_type_id = 1  left outer join dpa_party_contact _contacts_PHONE on _party.party_id = _contacts_PHONE.party_id and _contacts_PHONE.order_by_type = 1 and _contacts_PHONE.contact_type_id = 2  left outer join dpa_party_contact _contacts_MOBIL on _party.party_id = _contacts_MOBIL.party_id and _contacts_MOBIL.order_by_type = 1 and _contacts_MOBIL.contact_type_id = 3  left outer join (dpa_party_rel _first_sr_party_rel join dpa_party _first_sr_party on _first_sr_party_rel.from_party_id = _first_sr_party.party_id) on _party.party_id = _first_sr_party_rel.to_party_id and _first_sr_party_rel.party_rel_type_id = 2 and _first_sr_party_rel.to_party_order_by_type = 1 left outer join cpa_party_rel_type _first_sr_party_rel_type on _first_sr_party_rel.party_rel_type_id = _first_sr_party_rel_type.party_rel_type_id   WHERE EXISTS (SELECT * FROM dpa_party_role _party_role_ex WHERE _party_role_ex.party_id = _party.party_id and _party_role_ex.party_role_type_id in (1)) AND _party.dic ilike 'CZ%' AND _addresses_pernament.city ilike 'praha%' AND _party.full_name ilike '%tran%' AND _addresses_pernament.zip not ilike '%169%' limit 10001

**Comment by milant007** [comment]
tak jeste jeden bug u TEST01, kdyz si ho zobrazis a zajedes listou doprava a das setridit napr podle emailu, tak se rozhodi nadpisy sloupcu v gridu.

**Comment by jzelenka** [comment]
to jsi dela; v FF, v CH to nedela.

FF toho ma vic, co nefunguje, nevim jestli nerict ze pouze CH.
FF ma navic pomalejsi scrolovani v gridu.

**Comment by milant007** [comment]
ok, v tom pripade no problem! budu testovat pouze v CH a tam to skutecne nedela.

**Comment by jzelenka** [comment]
zaviram uklid.
