### ISSUE TITLE
Kontrolovat pristup dle tenanta pri otevirani detailu.

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#60]
Podarilo se mi woodoo s tenanty. Prihlasil jsem se do VOLVO SK, ale pouzil link na FA z VOLVO HU, a ten detail FA se mi otevrel presto ze to byl tenant VOLVO HU.

**Comment by jzelenka** [comment]
No jo, o tom tak nejak vim. Je to ve fronte.

**Comment by milant007** [comment]
nehori to, ale kdyz uz jsem na to narazil, tak jsem to napsal...

**Comment by jzelenka** [comment]
spravne :)

**Comment by jzelenka** [comment]
tohle uz je opravene, zkuste pretestovat.

**Comment by milant007** [comment]
Vypada to ok, ale vim, ze za nejaky konstalace mi to minuly tyden nejak v ramci prepinani tenantu zasvinilo, ale musi to zase nastat, ted uz to nenavodim...
