### ISSUE TITLE
Download Invoice Print

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#61]
Jak jsme vcera generovali pro SK ty hromadne FA, tak jsem psal, ze jednu musim otevrit updatem, pridat tam polozku sleva a znovu uzavrit. Tim padem u teto FA http://zauzoo.com/invoice/detail/8612?gridLocation=issuedInvoiceList je vicero PDF. Kdyz pak pustime funkci na stazeni PDFek "Download Invoice Print" tak pri volbe ZIP se stahne ta prvni, tedy bez slevy, kdyz ale zvolim PDF, tak pri tom spojovani se tam da ta spravna aktualni se slevou.

**Comment by jzelenka** [comment]
Musis na starych tiscich faktury - jsou tam celkem 3, takze 2 jsou zastarale - vyplnit v dco_document policko replacement_document_id  ideckem toho ktery ho nahradil, tedy toho aktualniho.
Takze jen jedna PDF faktura bude mit replacement_document_id = null.

Reopen to samozrejme bude delat automaticky.
Casem, az bude historie, tak skreju ty zastarele tisky i na detailu faktury a budou dostupne jen pres historii.
