### ISSUE TITLE
Uprava datumu pri vystaveni FA

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#62]
ted jsem narazil na:

Pokud vystavuji FA v ZZ a upravim datum vystaveni - Invoice date, tak chci aby se mi Tax Date, Due Date, v HU Delivery Date prepocitali. Pak si je mohu dodatecne doeditovat uplne jinak, ale pri zmene Invoice Date na jiny datum by se mely vsechny datumy prepocitat. Tax Date = Invoice Date, Due Date = Invoice Date + splatnost, delivery HU stejny princip.

Tax Date pak bude mit specialitu, ze pokud k Fa je navazany Dodaci list, tak se bude nabízet podle datumu dodaku, pokud budem delat FA z proforma FA, tak je Tax Date podle datumu uhrady a je tam tech podminek vicero. Ale to prijde az se sklady...

**Comment by jzelenka** [comment]
hotovo, pushnuto.

Jeste jsem to dal na issue hromadnych faktur, kde se ale dle invoiceDate meni jen taxDate.

**Comment by milant007** [comment]
a jeste pak nezapomen ze pri vastaveni hromadne FA das due date taky podle invoiceDate. Tam se neptas v te funkci, protoze samo kazdej zakaznik to muze mit jinak, ale na pozadi to podle invoiceDate + splatnost toho zakaznika nastavis.

**Comment by jzelenka** [comment]
to tam uz je.
Stejne jako deliveryDate pro HU
