### ISSUE TITLE
Contact persons 

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#64]
- Kdyz otevru grid contact persons, tak se mi nahore v zalozce objevi Customers. 
- Kdyz dam novy zaznam u contact persons, tak se mi priradi role customer namisto contact person

**Comment by jzelenka** [comment]
> Kdyz otevru grid contact persons, tak se mi nahore v zalozce objevi Customers.
myslis tohle:
![image](https://cloud.githubusercontent.com/assets/1957955/16036210/2bf01d32-321b-11e6-98cd-ba84858c613f.png)

**Comment by milant007** [comment]
jo a ted dej novou kontaktni ososbu

**Comment by jzelenka** [comment]
fixed, pushed, wait for (automatic) deploy on test (app and fe).
