### ISSUE TITLE
Zmena nazvu gridu

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#66]
ted behem testovani se Vitkovi podarilo aby zmizel(v TESTU) standardni grid Customers. Kdyz mi popsal kroky, tak chtel jen zkopirovat nejaky a vytvorit vlastni. Nicmene postupoval spatne.Dal novy, pak si vybral stavajici tam udelal upravy vcetne nazvu a dal ulozit. Stalo se to, ze prejmenoval a upravil parametry u stavajiciho gridu Customers.
Co bych udelal v tuto chvili je, ze pri editaci gridu by nemel jit uz editovat nazev toho gridu(alespon) a idealne aby i uzivatel ktery ten grid nezalozil jej ani nemohl editovat, pak by mu nezbylo nez dat copy grid...? 
Tyhle dva body by asi chtelo opravit, ale celkove jsou gridy a komu by se co melo zobrazovat a kdo by mohl editovat atd. na delsi diskusi...

**Comment by jzelenka** [comment]
Ja jsem to udelal tak, ze kdyz das novy nebo copy grid, tak je pak disablovany vyber gridu. Takze pak uz do editace existujiciho gridu nejde skocit.

Zakazovat editaci nazvu gridu je trochu omezujici....
Prava kdo muze editovat grid zatim neresim.

Kdyby se ti to nezdalo tak znovu otevri.
