### ISSUE TITLE
Contact person, Customer

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#67]
- zjednodusit vazbeni Kontaktni osoba zakaznik. Urcite nejak vynechat (mit moznost zadat pouze jako advanced) optionbox "from this party to selected party"... asi bych i vazbu nastavil tak, ze pokud je nekdo v roli customer a na druhy strane pouze v roli contact person tak i typ vazby predvyplnit. Pouze nekdo kdo je zaroven contact person i sales reppresentative tak se typ vazby musi zvolit.
- Jeste poznamka od Vitka, ze by nebylo spatny mit moznost nejen v karte customera vazbit ale i rovnou zadat kontaktni osobu(tak jako jde zalozit auto). Ona by se pak automaticky na tohoto customera navazala a contact person by se zalozil, a dal by se dovazbit kamkoliv jinam. do jineho zakaznika, nastavit mu jiny role atd.

**Comment by jzelenka** [comment]
Auto se zaklada odskokem na stranku "nove auto" akorat se predvyplni party.

Tady by mozna melo smysl zadavat kontaktni osobu v dialogovem okne? Aby se nemusel vracet...

U toho auta to ma takhle smysl jako to je, protoze pak zadava produktu v subgridu, ale u kontaktni osoby by se v dialogu ukazal jen vlastni formular.

**Comment by milant007** [comment]
ja bych to udelal jako to auto, at je stejna logika. a rovnou uz by byla predvyplnena zalozka relationships na te nove contact persone a pres back by se vratil na customera a tam uz by to v te relationship bylo videt taky ze je tam vazba?

**Comment by jzelenka** [comment]
ok

**Comment by milant007** [comment]
jeste je otazka, ten contact person uz muze v DB existovat, takze moznost vazbeni bych tam nechal i tak, ale kdyz nenajdu, tak zvolim zalozit a rovnou provazbit.

**Comment by jzelenka** [comment]
no samozrejme, tak pribude jen ikonka jako u auta...

**Comment by jzelenka** [comment]
hotove, pushnute.
