### ISSUE TITLE
Zadavani roli v party

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#68]
Kdyz zadavm role, tak zda by nesel checkbox ty role rovnou zaklikat vsechny co potrebuji a pridat jich vice najednou?

**Comment by jzelenka** [comment]
je to na testu, mrni na to.
je to v branchi, aby to slo lehce zrusit, tj. deploy na prod to tam nedostane, kdyz to odsouhlasis, mergnu to do masteru a pak si muses udelat deploy na prod.

**Comment by milant007** [comment]
to je vono, super, dej to do produkce
