### ISSUE TITLE
Import Party RO hotove

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#69]
Dokončil jsem import pro RO tenant 7. Na co jsem narazil:

- eviduji si nejake contract number. Ja jsem pro to zatim zalozil contact, ale asi bych to ted pridal k aditional IDS? Nebo az pak bude evidence dokumentu, tak nekde tam. Cesky Volvo si taky eviduje cely workflow dokumentu, kdy byl odeslan, kdy obdrzely odpoved a kdy to bylo podepsany atd. tak by se to melo zobecnit - nejen pro volvo.
- zakaznici co se maji fakturovat zpetne jsem zalozil roli retroactive a priradil ji tem co do toho spadaji. Otazka kam to zadavat - rola asi taky neni idealni. A jak to pak fakturovat v te hromadne fakturaci?

**Comment by milant007** [comment]
Doplneni:
- RO nepouziva IC, takze nesmi byt required field
- to jen pro info: v RO se u adres nekdy nepouziva ZIP code

**Comment by jzelenka** [comment]
> ad contract number

Feature (additional IDS) by bylo lepsi nez contact, ale protoze chceme udelat modul dokumentu/smluv, tak to zatim, nez ten modul udelame, nechme na tom contactu

> ad retroactive

spis se to hodi na feature, prejmenoval bych Additional IDS (kde je ted pouze Accounting Matching ID) na "Invoice Data" a byly by tam teda dve policka: "Accounting Matching ID" a "Retroactive Invoicing" (checkbox).

Co se tyce hromadne fakturace, staci asi kdyz bude mozne "Retroactive Invoicing" pridat do gridu a tim padem podle nej filtrovat, ne?

> ico

ok pro tenant.vat_rate_country = RO, bude ico uplne skryte.

**Comment by jzelenka** [comment]
A udelej nekde (treba na produkci, ja si pak zkopiruju DB do devu nebo i testu) RO tenanta, ta to muzu vyzkouset.

**Comment by jzelenka** [comment]
hotovo a nasazeno i na prod.

retroactive - smazana role, pridano do FEATURE, ktera je prejmenovana na Invoice Data
zaroven je v gridu sloupec Invoice delay.

Z duvodu budouci automatizace fakturace to neni checkbox ano/ne , ale textField, kam se ted dava hodnota 1m

contract number jsem nemenil.

ICO ma tenant RO skryte.
