### ISSUE TITLE
policka jsou sirsi nez nutna

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#7]
Kdyz si das Customers, tak Address Street nebo Address City je o dost sirsi nez je nutne i pro nejdelsi data v policku.

(lokalne se ti bude poprve nacitat dost dlouho, pak se to zrychli, je tam app. kes, jeste to budu resit)

**Comment by martinnemec3** [comment]
Sirka policek se vypocitava nasledovne:
1. zjisti se pocet X znaku nejdelsiho retezece
2. udela se element, do ktereho se vypise X krat pismeno C (C jsem vybral nahodne jako jedno z tech sirsich)
3. podle toho se nastavi min-width
Problem tady zpusobuje to, ze pismeno C je o dost sirsi nez prumerna sirka znaku v address street. Je vic pristupu jak tohle resit
* sirku delat presne podle nejdelsiho textu - problem je ze jich muze byt vic a hledat ten nejdesli v px by uz dost spomalovalo, navic neni nutnost, ze znakove nejdelsi text bude i absolutne nejdesli (v px). Priklad: iiiiiiiiiiiiiii vs. AAAAAAAAAA.
Mne prislo asi jedno, jestli tu delku spocitam z retezce poskladanyho z opakujiciho se jednoho pismene nebo vyberu jeden nahodnej z nejdelsich retezcu co tam jsou.
Takze moznosti:
* vybrat jiny pismeno (muze pak delat problem tam kde jsou retezce jen z velkych pismen napr. ICO)
* zkusit to udelat z nahodnyho nejdelsiho a uvidi se

**Comment by jzelenka** [comment]
Zkus prvni nejdelsi

**Comment by martinnemec3** [comment]
Nastaveno (branch issue#7). Jeste zvazit, jestli nepricist par pixelu (nektery pole kde je nejdelsi ze sloupce jeho nazev maji pak tyto nazvy blizko u sebe)

**Comment by jzelenka** [comment]
Takhle je to dobry, udelej pull request na fe, ja to mergnu.

**Comment by jzelenka** [comment]
Prijde me ze je to porad zbytecne siroke:
V Kontaktech, vyhledej treba podle vala, najde to 2 radky, kdyz to zuzis aby se objevil horiz. scrollbar, tak je u emailu porad zbytecne moc mista....

![image](https://cloud.githubusercontent.com/assets/1957955/10304338/cff789c4-6c19-11e5-9981-f3a948c32a4d.png)

**Comment by martinnemec3** [comment]
Mel jsem spatny pismo v tech pomocnych elementech, podle kterych jsem pocital minimalni sirku. Opraveno (+ pridano 5px jako rezerva - bunky maji asi nejakej margin, padding)
