### ISSUE TITLE
Hromadne prirazeni balicku

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#70]
Pozadavek z SK:
Zdravím,
Cchel by som sa spýtať, či by išlo nejakým spôsobom ošetriť, keď mám nalsedovný prípad...vozidlo nefakturujem, resp nastavím ukončenie platnosti vozidla na 22-6-2016 a v 7.mesiaci ho chcem obnoviť, resp obnoviť viac vozidiel. Ked si to davam cez vyber vozidiel, zaklikam si ich a nastavim balicek s ddatumom zaciatonym od 1,7,2016 a koncovy nevyplnim, tak sa to po ulozenie neprejavi aj na vozidle...prejavi sa datum OD, ale datum DO ostane nezmeneny...
- Zkousel jsem to a opravdu datum DO zustane, ale potrebuji rict ze platnost DO je zase neomezena...

**Comment by jzelenka** [comment]
Fixed, pushed.

Potreboval jsem rozlisit situaci kdy se datumy ProductVehicle nevyplni protoze je nechteji menit (protoze treba chteji menit jen cenu) od situace kdy je chteji nastavit na null (to je tato situace u validTo).

Takze jsem pridal checkbox Product dates, ktery kdyz neni zaskrtnuty tak jsou datumy ProductVehicle skryte a samozrejme se neprovede jejich update a insert je vlozi null (1 situace) a teprve kdyz se zaskrnou tak se pouziji a to uz samozrejme vzdy, i kdyz jsou null (druha situace = tento bug).

**Comment by milant007** [comment]
SUPER, myslim si ze jsi to vyresil tim zaskrtavadlem idealne.
