### ISSUE TITLE
Vyhledávání v šabloně

### ISSUE THREAD

**Issue by krivohlavek** [zauzoo/app#74]
V sablone nejde vyhledavat. Ctrl+f funguje jen kdyz kliknu mimo textareu s kodem, ale pak to hleda jen v casti, ktera se vejde na obrazovku - ne v celem kodu.

**Comment by jzelenka** [comment]
Opraveno, Ctrl+f, kdyz kliknuto na textAree, vyvola nyni specialni search dialog.
Ted je to na testu.
