### ISSUE TITLE
Chyba pri hromadnem generovani FA

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#77]
Na TESTu pri hromadnem generovani FA to vyhodi chybu: **Rate EUR/RON not found for invoice null**
i presto ze kurz se v menu nabidne(4.49235632).

**Comment by jzelenka** [comment]
fixed, pushed (app).

(znovu rikam - "pushed" znamena ze se to automaticky nasadi na test, ale ne na produkci (protoze push znamena vlozeni do githubu a jenkins ma build trigger - čekuje změny každých 5 min a když nastane, tak uděla deploy na test))
