### ISSUE TITLE
Bugy v hromadne fakturaci RO

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#78]
1. pokud zvolim na TESTu v customerech grid Valid Price, tak se mi nabidne 302 zakazniku k fakturaci, ale po prepare issue jich vyhodi jen 299, takze tri se nekam ztrati. Jednoho jsem si nasel **CRISELY SRL** a nevidim na nem nic odlisneho proti ostatnim
2. kdyz si zvolim v customerech grid valid price, tak je tam pole Invoice delay abych si rozdelil FA zpetnou a aktualni. Problem je pri dofiltrovani. Pokud dam equal = 1m tak ok, ale obracene asi kvuli null hodnote v poli mi to na not equal/not contains 1m nevrati zadny zaznam

**Comment by milant007** [comment]
3. jak mas v menu prepare issue next month, tak RO potrebuji previous month, ale to neni tak podstatny, ja si ten datum te periody zadal rucne. Ale u zakaznika v TESTu **AG TRANS SRL** jsem k 30.6. ukoncil platnost balicku. pote dal generovat FA od 1.6.2016 do 30.6.2016 a po spusteni prepare issue se nepripravila.

**Comment by jzelenka** [comment]
ad 1)
CRISELY ma jen 1 vehicle a to neni aktivni:  active = false.
na RO v testu jich je celkem 28
select * from dpr_vehicle where tenant_id = 7 and active = false 

tohleto active true/false je i napriklad na party a slouzi to k vypinani mrtvych customeru / aut, ktere nejsou smazat protoze treba maji invoice, nebo je tam chceme mit kvuli treba nejakemu historickemu reportingu apod.

Akorat na to neni GUI, protoze to nechci mit jako policko ale jako nejakou hezkou ikonku, takze jsem se k tomu jeste nedostal.

Jinak vypis Customeru, kteri vypadli z fakturace + duvod tam byl, ale na tvoji zadost jsem to vyhodil....

**Comment by milant007** [comment]
Ad1) tak v tom pripade dej cenu 0 do Valid Price aby bylo jasny, ze to auto je mrtvy. Ted mi doslo ze pri importu tam bylo par aut ve stavu **PAUSED** a ja je tady hodil jako active = false...
Ten vypis je takhle dobre, to nech. jen jsem potreboval vedet proc to tam nespadlo.

**Comment by jzelenka** [comment]
ok

**Comment by jzelenka** [comment]
2) opraveno, 
funguje not equal i not contains.
pushnuto.

**Comment by jzelenka** [comment]
ad 3)
platne balicky se vybiraji vzhledem k invoiceDate.

Maji se tedy vybirat k startPeriod nebo endPeriod?

Doufam ze nechces pripady kdy balicek konci nebo zacina nebo oboji uprostred periody dopocitavat pomrnou cast....

**Comment by milant007** [comment]
Ad3) zadnej pomer, to urcite ne, ale muze se overit platnost pro oba datumy(start i end) soucasne. Oba tam musej spadnout a splnovat podminku validfrom <= start/end <= validto.

**Comment by jzelenka** [comment]
ad 3) fixed, pushed.

**Comment by milant007** [comment]
Ad3) uz neco vyplavalo. 
- but tam dej pouze "end date". Oni si valid from v SK zadali k aktualnimu dni a hned fakturovali... sorry, ale snad to nebude takovej vopruz tu podminku zmenit. :-(
- nebo by se musela dat chybova hlaska po prepare issue ze tam plati pouze jeden z tech datumu start/end a ten druhej ji nesplnuje?

**Comment by jzelenka** [comment]
ad3)
abychom to porad nemenili jak kdo vyplni data, tak navrhuju tohle (prijde me to nejspravnejsi) :
- pokud se do platnosti balicku vejde jen cast invoice period, tak se balicek zahrne, ale castka se spocita pomerove a v prepare issue bude warning (zluta/oranzova) hlaska, ze je na fakture jen cast balicku, aby si to pripadne mohli opravit, pokud doopravdy nechteji pomerovou cast.
- pokud platnost balicku bude uplne mimo invoice period tak to bude jako dosud - proste se vynecha, a pokud zakaznik nebude mit jine (nevynechane) balicky, tak se fakura vynecha.

Dalsi platnosti (treba platnost ceny, vat rate, currency rate) se berou k period start date.

Kdyz nebude vyplnene invoice period (spise pro jine zakazniky nez volvo) tak se vsechny platnosti (produktu, balicku, cen, vat, currency rate) berou k invoice date.

**Comment by milant007** [comment]
Souhlas, ale aby hlasky tohoto typu sly jako prvni, a pak az ty co jsou Ok.

Platnosti ceny hod asi k end period, nez se to naucej zadavat, tak platnosti davaj vetsinou spravne k poslednimu dni kdy ma skoncit . Pokud ale end period jeste nenastal, tak to das taky dle invoice date.

Pokud nechci pouzit periodu, tak bych dal nejaky disable checkbox, protoze promazat datumy moc uzivatel nenapadne. A pak jak pises ke dni vystaveni.

**Comment by jzelenka** [comment]
Co myslis tim "pokud end period jeste nenastal" ?

**Comment by milant007** [comment]
napr. vystavuji dnes 20.7. FA za cervenec ale period je 1.7. - 31.7.

**Comment by milant007** [comment]
jeste me doslo, ze u te hromadne FA bych dal This Month a Previous Month. Nesetkal jsem se s fakturaci dopredu. Bud se fakturuje za aktualni periodu nebo za tu co skoncila...

**Comment by jzelenka** [comment]
Melo by to byt vse opravene:
- pokud je ProductVehicle platne jen v casti InvoicePeriod, zobrazi se warning, faktura lze vystavit, cena je pokracena
- pokud existuje platna cena jen v casti InvoicePeriod nebo se cena behem invoice period meni, zobrazi se warning, faktura lze vystavit, cena je spocitana "spravne" (den po dni podle platne ceny v ten den).

Jeste mam poznamku - v soucasnosti vypadne zakaznik z fakturace pokud nema zadny platny balicek nebo pokud tento balicek nema platnou cenu.  (nema platny = nema vubec prusecik s InvoicePeriod).
Zmenil bych to tak, ze vypadne jen kdyz nema platny balicek, ale pokud nema platnou cenu tak nevypadne a bude tam chyba.  Protoze uzivatele by si balicky "dopredu" meli pripravovat pomoci platnosti balicku a ne ceny, protoze cena je slozita (dopocitava se ze 3 urovni dle priorit). Potom kdyz zakaznik vypadne z fakturace tak bude jasne ze nema platny balicek, zatimco takhle se musi jeste prohrabavat ceny.

Problem s rumunskym casovym pasmem je take vyresen.

**Comment by milant007** [comment]
ohledne ty platnosti balicku a nulovych cen, ta poznama je na miste, ale ono to bohuzel neni tak jednoduchy. :-( 
- Oni si eviduji ze zakaznik pouziva i balicek ktery je aktivni a pri tom je nacenen za 0(v ramci promo akce, protoze ma tolik balicku, ze uz mu jeden dali zdarma, atd.). cili kdyby tam bylo, ze balicek neni platny, tak by z toho vyrozumneli ze je neaktivni coz neni pravda. Jedine to vymyslet jinak...
- Pro priklad ja to mam v MD pro Volvo CZ nasledovne: ja kaslu na platnot balicku(ani to nemuzou zadat) a beru to jen podle ceny, pokud je > 0 tak fakturuji. Kdyz skonci platnost balicku tak si balicek z auta uplne smazou...

Funkcionalitu jdu ted vyzkouset...

**Comment by jzelenka** [comment]
No a nemel by se v tomto pripade  (aktivni balicek ale v ramci promo akce za 0) na fakture objevit. ale za 0?  Tak by se odlisilo "nema cenu = chyba" od  "je zadarmo"  a navic vy obsah faktury sedel se skutecne poskytovanymi sluzbami.
Pouze pokud by vsechny balicky byly za 0, a tedy celkova cena faktury by byla 0, tak by se faktura vynechala.

**Comment by milant007** [comment]
To by slo z hlediska funkcnosti, ale nekteri zakaznici si nepreji nulove ceny zobrazovat.
- takze ted bych to udelal presne tak jak pises, ale jindra upravi layouty tak, aby se nulove polozky na FA nezobrazovaly.  A pro koncoveho zakaznika bude FA po uprave vypadat naprosto stejne.
- a pokud by nekdy prisel pozadavek, ze si nektery zakaznik nulove ceny preje na FA videt, protoze mu to dela dobre, tak by se udelal feature "zobrazit nulove ceny". ale ted bych to neresil...

**Comment by jzelenka** [comment]
Takze je to udelane:
- pokud neni platny productVehicle naceneny (po cely interval) - je to chyba
- pokud je naceneny nulovou cenou - neni to chyba a polozka si prida. Tj. pokud nechcete nulove polozky, tak je musite vynechat v tisku.
- ale pokud ma faktura vsechny polozky nulove, tak se cela vynecha

**Comment by milant007** [comment]
super to je ono, jeste oteviram ale uz jen na Jindru aby upravil pro tisk

**Comment by krivohlavek** [comment]
Upraveno. Na faktuře se s 0 balíčky nepočítá (nezobrazí se, neovlivňují jednotkovou cenu a množství). V příloze 0 balíčky vidět jsou. Kdyby to vadilo, tak to taky odstraním.
