### ISSUE TITLE
oprava plneni dpa_party_rel

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#8]
Do `dpa_party_rel` jsem pridal sloupce:
`from_party_order_by_type` 
`to_party_order_by_type`

ktere vyjadruji poradi vazby pro dany typ a vzhledem k from_party respektive to_party

Priklad vazeb:

          Novak ->SalesRep->  CEZ   :  from_party_order_by_type = 1, to_party_order_by_type = 1
          Novak ->SalesRep->  CS     :  from_party_order_by_type = 2, to_party_order_by_type = 1
          Dvorak ->SalesRep->  CEZ   : from_party_order_by_type = 1, to_party_order_by_type = 2

Bez toho nelze udelat do gridu Customers policka *Prvni SalesRep*, *Druhy SaleRep*

**Comment by jzelenka** [comment]
Jo a potrebuju teda je naplnit spravnyma hodnotama, nyni maji vsude 1 (jsou not null)

**Comment by jzelenka** [comment]
Analogicka situace je u PartyContact. Ale tam to zatim nehori protoze pro dany PartyContactType (email, phone, mobil) ma kazda party jen jeden radek.

Takze pridam order sloupec (jako jsem pridal do PartyRel),  `dpa_party_contact.order_by_type` a dam ho vsude na 1.  
Protoze je vsude jen jeden radek nemusis opravovat data, jen si oprav skript.

U adresy to zatim neresim, protoze tam zobrazuju typ PERMANENT a ten bude vzdy jen jeden.

**Comment by milant007** [comment]
Skripty upravim

Obchodni zastupci ve volvo nerozlisujou prioritu, dokonce nekdy vyplnujou jen 2 nekdy jen 1. A funkce co jim neco rozesila nebo tak to neresi. To ze tam je 1 a 2 je pouze nesmyslenej datovej model kluku z MD v AT. Pokud to ale potrebujes nejak rozdelit z duvodu funkcnosti, tak upravim skript a prioritu jim pridelim i tak.

**Comment by milant007** [comment]
Prozatim jsem napsal skript, kterej to upravi, podle potreb. v gridu uz se to zobrazuje spravne. ten importovaci nevim zda je nutny menit, protoze ted priority nejsou a tento narovna jak obchodni zastupce tak i kontaktni osoby najednou a muze se pustit po tom co se vsechno naimortuje?
(a kdybych si tve zadani prectl az do konce, tak bys mi byval ani nemusel volat viz. tato veta: "Bez toho nelze udelat do gridu Customers policka Prvni SalesRep, Druhy SaleRep") :-)

**Comment by jzelenka** [comment]
Jasne, import je vase vec jak to udelate....

**Comment by jzelenka** [comment]
Mely by jit vytvorit tyto 3 unique indexy:

      alter table dpa_party_rel add constraint uc_dpa_party_rel_01 unique (from_party_id, party_rel_type_id, from_party_order_by_type);
      alter table dpa_party_rel add constraint uc_dpa_party_rel_02 unique (to_party_id, party_rel_type_id, to_party_order_by_type);
      alter table dpa_party_rel add constraint uc_dpa_party_rel_03 unique (from_party_id, to_party_id, party_rel_type_id);

ten prvni nejde....

muzes zjisit pomoci:

`select from_party_id, party_rel_type_id, from_party_order_by_type, count(*) from dpa_party_rel group by from_party_id, party_rel_type_id, from_party_order_by_type having count(*) > 1`

Kdyz treba vezmu toho prvniho:
`select * from dpa_party_rel where from_party_id = 2337`

kdyz pominu fakt ze party_id 2337 Zbynek Krejcir je Sales Rep pro 32 firem, teda jako kdyz predpokladam, ze je to spravne, tak by `from_party_order_by_type` melo mit hodnoty 1 az 32, a ne vsude 1.

**Comment by milant007** [comment]
jsem hnup, mne nedoslo ze obchodni zastupci mohou byt ve vice firmach. ja jak jsem to vymyslel pro kontaktni osoby kde to mu tak neni a pak to rovnou bouchnul i pro obchodaky, tak jsem zapomnel ze tam je to hlavne obracenne! :-(
takze jsem ten skript zkopiroval a "to_" dal nahradit "from_"
Index uz prosel.
