### ISSUE TITLE
Dodatečný vodoznak ve stornované faktuře

### ISSUE THREAD

**Issue by krivohlavek** [zauzoo/app#81]
Při stornování faktury se v přehledu přeškrtne a v detailu je vodotisk. Ale chybí nějaké označení na pdf. Pokud zákazník vybere všechny soubory a dá export do pdf, tak se mu stáhne stornovaná faktura a není nijak označena. U exportů do účetnictví si to filtruju, pdf ale nejsem schopen ovlivnit. Lze dodatečně přihodit nějaký vodoznak do daného pdf (tak aby se nemuselo vytvářet PDF znovu)?

**Comment by jzelenka** [comment]
tohle je hotove. Prida se to do PDFka pri cancelovani.  Tedy stare zrusene to nemaji.
