### ISSUE TITLE
Kopírovaní záznamů dpr_products

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#83]
Pri kopirovani zaznamu v dpr_product ktery je v tenant group se nekopiruji sazby dph:

- bud udelat GUI kde to bude moci uzivatel, ktery je definovan i pro ostatni tenanty zmenit/doplnit
- nebo rovnou kopirovat tu samou sazbu
- nebo alespon upozornit uzivatele ve chvili kdy na takovou polozku vystavuje FA, ze to nelze protoze neni sazba DPH.

**Comment by jzelenka** [comment]
asi to bude:
> bud udelat GUI kde to bude moci uzivatel, ktery je definovan i pro ostatni tenanty zmenit/doplnit

protoze:
> nebo rovnou kopirovat tu samou sazbu

nejde udelat - jak poznam ze to je stejna sazba, kdyz pro kazdou zemi jsou sazby (tedy typy - zakladni, snizena....) nadefinove zvlast?  (to jsme udelali prave protoze ma kazda zeme jiny pocet pasem)

> nebo alespon upozornit uzivatele ve chvili kdy na takovou polozku vystavuje FA, ze to nelze protoze neni sazba DPH.

to by melo nejak fungovat - v hromadne fakturaci by mel vyjet error a normalni fakturaci se nenacte zadna sazba a tim padem nepujde radek faktury ulozit.  Alespon doufam ze to tak je, nezkousel jsem to.

**Comment by milant007** [comment]
> nebo alespon upozornit uzivatele ve chvili kdy na takovou polozku vystavuje FA, ze to nelze protoze neni sazba DPH.

Pokud toto funguje tak bych to neresil, zkopiruji si aktualni verzi na TEST, vyzkousim. Pokud to tak bude tak bych to uzavrel. :)

**Comment by milant007** [comment]
Vyzkouseno v TESTu a funguje. upozornuje jak hromadna tak pridat all vehicles, kdyz pridavam product, tak to pole vyzaduje.... ja bych to zavrel.
