### ISSUE TITLE
totalPriceLcy ve Volvo RO

### ISSUE THREAD

**Issue by krivohlavek** [zauzoo/app#85]
Volvo zaregistrovalo špatný součet v elementu totalPriceLcy, který používám jako celkovou částku pro zaplacení (kvůli zaokrouhlování mám používat toto pole a nemám to dělat v šabloně). Konkrétní příklad je  inovice ID 9759  (Invoice number TIS201610317). Částka bez daně je 11125,70 + daň 2225,14  má dát 13350,84, ale v xml leze 13350,85.  Mám speciálně pro RO sčítat částky, nebo bude zaokrouhlení upraveno? Předpokládám, že chyba bude v tom, že se zaokrouhluje až na konci, zatímco dílčí hodnoty jsou zaokrouhleny zvlášť.  Kdyby v tom bylo něco jiného, tak konzultace s Milanem (já jen přeposílám bug co přišel na mail).

```
<priceWithoutVatLcy>11125.70000000</priceWithoutVatLcy>
<vatAmountLcy>2225.14000000</vatAmountLcy>
<totalPriceLcy>13350.85000000</totalPriceLcy>
```

**Comment by jzelenka** [comment]
Urcite v sablone nic nescitej, sablona ma jen zobrazovat.
Ano, chyba je zpusobena zaokrouhlovanim, presneji receno tim, ze na Invoice soucty nepocitam, ale beru vsechny polozky z sum(InvoiceItem) a pak to zaokrouhlim. Pridavam obrazek kde to je pekne videt:

![image](https://cloud.githubusercontent.com/assets/1957955/18026334/391e80ae-6c43-11e6-9b9e-996887289186.png)

Predpokladam, ze je nutne aby na invoice platilo `priceWithoutVat + vatAmount = totalPrice`, takze to musime nejak resit:

1. jen zmenit vypocet tak, abych totalPrice scital az na fakture. Potom nebude sedet `zaokrouhleny sum(invoiceItem.totalPrice) =  invoice.totalPrice` - lisit se bude max o 0,01 (pri currency.decimal_places = 2)

2. pridat policko -  `totalPriceSumDiff' kde bude ten 0,01 a na invoice bude platit:

     `priceWithoutVat + vatAmount = totalPrice`
     `zaokrouhleny sum(invoiceItem.totalPrice) + totalPriceSumDiff=  totalPrice`

Protoze to same jako na  `priceWithoutVat + vatAmount = totalPrice` nastava jeste na `basePrice + totalAdjustmentAmount = priceWithoutVat` melo by se na fakture pocitat i priceWithoutVat, takze by se jednalo o 4 nove xxxSumDiff pole (vcetne lcy variant).

Nastava to dost casto - 2x na totalPrice, 500x na totalPriceLcy
  
@milant007 ?

**Comment by milant007** [comment]
A kdybychom pouzivali monetary_rounding_lcy ? Pokud by bylo 2 tak bude zaokrouhlovat uz invoiceItem.totalPrice na dve mista a tim padem soucty a vse dalsi se nemusi resit?

**Comment by jzelenka** [comment]
co to je monetary_rounding_lcy ?
pokud by monetary_rounding byl 2, tak skutecne uz vse na itemech je na 2 mista a nemusi se nic resit.

**Comment by milant007** [comment]
Na obrazku(vyrez z PDF) je videt, ze nesedi ani soucet polozek. Ucetni se mi zatim nepodarilo dovolat. :-(

Nicmene jsem zkusil vystavit FA na testu s monetary rounding 2 a soucty sedi. Myslim, ze by to mohlo byt ok, ale uvidime co na to reknou. Finalni castka se lisi o 0,25 RON.

![invoice](https://cloud.githubusercontent.com/assets/13977376/18050773/e51a7aa8-6df0-11e6-8cf6-3404bee86e99.png)

**Comment by jzelenka** [comment]
cislo faktury?

**Comment by milant007** [comment]
V testu se ted jedna o tuto nove vstavenou FA TIS201610618.
Zaklad bez DPH je 11125,93. DPH to ale diky zaokrouhlenemu souctu DPH polozek spocitalo na 2225,17. Kdyz ale spocitas DPH primo z te castky tak vychazi 2225,186 tedy zaokrouhlene 2225,19. Zda to takhle muze byt opravdu netusim, pockame co mi k tomu rekne ucetni.

**Comment by jzelenka** [comment]
V tomto pripade jsi dal monetary rounding = 2, takze polozky se zaokrouhluji na 2 desetinna mista.
Jak je videt, tak to nepomohlo aby se to rovnalo, je to logicke, vcera jsme si to neuvedomili. Kdyby se na polozkach zaokrouhoval jen priceWithoutVat a ostatni ne, tak by to asi pomohlo, jenze vzhledem k tomu ze predtim jsou jeste slevy kde je stejny problem a casem tam budou jeste ty slevy z cele faktury, tak bych touhle cestou nesel. Navic stejne muze nekdy nekomu vadit mala presnost a bylo by to zase v haji.

Takze navrhuju nechavat vetsi presnost na polozkach, treba tech 6 a predelat vypocet na fakture aby se pocitalo az na fakture kaskadou se zaokrouhlovanim jednotlivych mezivysledku - pak to bude sedet pri rucnim prepocitani.

Tim padem budou lidi spokojeni, ale vzniknou nam ty rozdily mezi napr `invoice.totalPrice ≠ sum(invoiceItem.totalPrice)`

Co je resit misto novymi policky na fakture, specialnim radkem do invoiceItem ?
Tedy tento radek by mel item_type = "ROUNDINGDIFF"   a v invoiceItem.totalPrice apod by mel tu differenci aby soucty vysly s tim co je na fakture.

V tisku by se vyloucil (nebo nevyloucil kdyz by nekdo prudil ze mu to nevychazi kdyz to secte).

**Comment by milant007** [comment]
Takže po rozhovoru s účetní:
Monetary rounding = 2 je **ok** A to i když následný výpočet DPH proti součtu na položkách se liší. Čili takto by to mohlo být. 
**ALE** 
1. Nevime jaky jsou zakony v HU, RO, BG
2. Heiru pouziva cenotvorbu(unit price) i na FA na 5 desetinnych mist u polozek, ale az finalni castka NETO, DPH a TOTAL je na dve desetinna mista.
3. Pri prenosu do účetnictví některé účetní programy(FlexiBee, Pohoda) ignorují částku DPH přesto že ji pošleš a generují si ji sami. Takže by mohl být problém s převody do účetnictví. Ovšem to může být i když ji vypočítáme až z netto částky, ale pravděpodobnost ja asi menší...

Jeste by to mohlo vyresit toto, ted jsem si to projel na kalkulacce. 
Monetary rounding by urcoval pouze cenu za unit po vsech slevach atd. vsechno ostatni by proste bylo na 2 desetinna mista. Nebo nove pole unit_monetary_rounding a monetary rounding ponechat.
V tomto pripade by to spocitalo takto: _Netto_ 11125,71 _DPH_ 2225,13 _Total_ 13350,84
Porad by tam ale byl rozdil na DPH o 0,01

**Comment by milant007** [comment]
**Takze po konzultaci s ucetni udelame ten extra radek.**

**Comment by jzelenka** [comment]
Je to tam.
Ted uz by soucety polozek a vypoctena cisla na urovni faktury mely vzdy sedet.
Pokud bude potreba nejake soucty v grupovani (jako ted per produkt pres vsechny auta) tak se problem muze samozreme objevit znovu. Protoze grupovani muze byt ruzne, je jedina rada nezaokrouhlovat soucty v grupovani.

@krivohlavek Jindro ten radek, pokud ho budes chtit vyloucit ze sablony, poznas takto:

      <items>
         <itemType>ROUNDINGDIFF</itemType>


JInak jse provedl upgrade ruznych FE knihoven, takze se muze stat ze se neco rozbije.... tak to radeji chvili nechte v testu.
