### ISSUE TITLE
Assign Product neprirazuje platnost

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#86]
V TESTu jsem zkousel priradit platnost balicku pomoci assign product. Uz na tech autech ten balicek byl prirazen, ale chtel jsem zmenit jeho platnost. Nic se vsak nestalo.
Konkretne tenant RO, auta zakaznika INSERT AUTO SERVICE SRL a Product Positioning, ktery je na autech prirazen a chtel jsem dat platnost od 1.1.2017.

**Comment by jzelenka** [comment]
Opraveno, omylem jsem vypustil ten checkbox, ktery ridi jestli se datum produktu nastavuje.
pushed na test.
