### ISSUE TITLE
Automaticke posilani vystavenych FA

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#87]
#### 4. Automaticke posilani vystavenych FA
- musi byt vystavena nova FA na zakaznika
- zakaznik ma alespon jednu kontaktni osobu v roli cpa_party_role_type.party_role_type_id = 7(Email invoice), pokud jich ma vice slozim emailove adresy dohromady aby se pote poslal 1 email
- pro odeslani FA budou dve funkce:
 1. pro odeslani emailem - posle emailem
 2. pro odeslani postou - spoji PDFka(volba simplex (jen spoji), duplex (sudy stranky doplni prazdnym papirem pro oboustranny tisk) ) pro moznost odeslani na tiskarnu
- u obou funkci bude priznak ze jiz byla odeslana. Cilem je aby kazda FA byla odeslana prave 1x. Pokud FA vytisknu pres nahled a ne pres tuto funkci mohu pouzit "zaskrtavadlo" Mark as Send aby ji zaradil do odeslanych faktur. Pokud u jiz odeslane FA udelam reopen Mark as Send se odoznaci. Pro bod 1(email) muze byt nejaky parametr v tenantovi ze po mnou zadanem case se FA emailem odesle sama.
**NASTAVENI**
- moznost nastavit mail, ze ktereho se bude PDF posilat. Pozor, protoze Volvo posila sluzby za Dynafleet(Volvo) a Optifleet(Renault), tak chteji aby i email si mohli nastavit podle Profit Center. Ale pokud nenastavim profit center tak se bude posilat jedna sablona za vsechny Profit centra.
- moznost nastavit reply to, Volvo pouziva neco@zauzoo.com, ale kdyz da zakaznik odpovedet, aby odpoved sla na mail zadany uzivatelem.
- v pripade ze nebudou pouzivat email ZauZoo(Volvo BUDE) tak mit moznost u vlastniho emailu nastavit SMTP.
- mel bych mit moznost si nastavit html text emailu. A zase v tele emailu je odlisny text pro kazdy profit center.
- moznost nastavit, ze pokud neodeslu manualne, ze se PDF po vystaveni odesle sama za mnou zadanou dobu nebo pripadne v konkretni cas az nastane.
- a jeste bych bral v potaz vicejazycnost textu...

:boom:
- každý den event job pro tento eventType vygeneruje `ScheduledEvent` pro nově vytvořené nebo změněné po tomto eventu, faktury.
- event se standardně zpracuje, algoritmus grupování je 1 email per faktura na všechny příjemce.

**Comment by jzelenka** [comment]
Je to hotove.
Co neni:
 - moznost nastavit vlastni SMTP - to se me moc nezda
 - job, ktery po nejake dobe odesle fakturu (emailem) sam  - to dodelam casem
 - duplex print (doplneni prazdnych stranek - dodelam

### Odeslani Postou
- Do download dialogu pribyla moznost `Mark Invoices as Sent via post`, ktera jednak zpusobi zapsani udalosti INVOICE_SENT_POST a jednak vylouci uz poslane a nebo ty ktere jdou poslat emailem, coz jsou faktury jejich zakaznik nema zadnou emailovou adresu (nema ani kontaktni osobu s roli EMAIL a s kontaktem typu email nebo invoicing email ani vlastni zakaznik nema kontakt typu Invoicing email) 
- uz poslane lze poslat znovu checkboxem `Include already sent invoices`. Jako poslana se bere i odeslana emailem.

### Odeslani Emailem
- Faktury, ktere jdou poslat emailem se poslou pres podobny dialog jako Issue invoice.
- v dev a test prostredi se emaily nahradi emailem na party prihlaseneho uzivatele (takze si na sebe nastav email, jinak se v testu zadny neposle).
 
### jak je to datove
jednotlive udalosti se zapisuji do tabulky dco_event_history, nic tedy neni primo na fakture.
Az bude reopen faktury tak poznam ze faktura sice ma uz event odeslano, ale potom nastala udalost reopen a znovu issue, a od te doby nemela znovu odeslano a tim padem je k odeslani....

Historie udalosti faktury (customera a casem vseho) je pod novou ikonkou vlevo nahore na detailu, ale zatim neni hezka.


### Konfigurace Emailu
- v menu Administrace je polozka `Event Types` analogicka jako document Types:
 - udela se eventType, ktery se navaze na Event Type (no jo, jmenuje se to stejne..), v tomto pripade INVOICE_SENT_EMAIL a ktery se priradi tenantum nebo tenant grupam.
 - potom se pro tento eventType udela jedna nebo vice `eventTemplates`. Vice jich bude pro odliseni profitCenter a jazyka. Kdyz se necha profitCenter a jazyk null tak staci jedna.
- V `eventTemplates` se nastavuje adresa from (pokud neni tak failbackne na defaultni v zauzoo konfiguraci), adresa replyTo, subject a text.
- Text by asi mel byt html a je to template - daji se tam dosazovat hodnoty. Zatim je tam k dispozici Invoice a prihlaseny uzivatel a aktualni datum. Viz jak jsem to nastavil na testu.


Zatim se neda filtrovat hlavni grid na odeslane/neodeslane a  odesilane emailem/postou, ale je to v planu. Takze to zatim filtrujes az na tech dialozich, kde jak to zaskrtavas tak se meni pocty.

**Comment by jzelenka** [comment]
duplex je hotovy

**Comment by jzelenka** [comment]
subject uz je taky sablona, stejna syntaxe jako body, pr:

Elektronicka faktura cislo ${Invoice.invoiceNumber}

**Comment by jzelenka** [comment]
Mam k tomu otazku - ja tam na ruznych mistech pomerne slozite zjistuju jestli ma nejakou emailovou adresu k poslani faktury nebo ne, abych rozhodl jestli je faktura posilana emailem nebo postou.

Podle me by to ale melo byt proste nastavene na customerovi, typ poslani faktury EMAIL x POST.
Protoze co kdyz nekdo bude chtit POST a zaroven ma konktatni osobu s emailem? 
Nehlede na to, ze kdyby v budoucnu existovala nejaka dalsi moznost tak soucasnym stavem by to uz neslo. Je to sice vice nastaveni, ale mohli bychom inicializovat pomoci soucasnych selectu a policko udelat pro customera povinne.

Vsechny selecty ktere se porad pousti v dialogovych oknech stahovani tisku a emailovani pri zaskrtavani tech checkboxu by se hodne zjednodusila.

Pri vlastnim odeslani faktury emailem by nove mohlo dojit k situaci, kdy je to nakonfigurovane, ale emailova adresa neexistuje - to by pak byla chyba.

**Comment by milant007** [comment]
Ano, muze byt. Alespon bude na prvni pohled v gridu Customera videt jak to je, a bude to i jednodussi vyfiltrovat.
Pak bych ale pri zalozeni FA tento priznak prenasel taky a to takovy, jaky zrovna Customer v tu chvili ma. Zase dobry kvuli rychlemu zafiltrovani a historii jak se to odesilalo. Pripadne moznosti to jeste na te FA zmenit...? Pokud by to tak bylo, tak bych akorat u kopirovani FA toto po zkopirovani vkladal aktualni z dat Customera a nekopiroval.

**Comment by jzelenka** [comment]
Ok,
1. pole na customerovi defaultInvoiceSendingType (POST, EMAIL), ted predvyplnim selectem, u novych customeru povinne a predvyplnene bude POST
2. na fakture totez pole sendingType, predvyplnene z customera, lze zmenit, bude skryte pod tim rozklikem. Na starych fakturach vyplnim selectem, na novych povinne.
3. pri kopirovani faktury se to vezme cerstve ze zakaznika.

**Comment by jzelenka** [comment]
je to hotove (job ma samostatny bug), stalo by za to kdyby to nekdo prepsal do dokumentace - wiki.

**Comment by milant007** [comment]
popisu to

**Comment by milant007** [comment]
Jeste jedna drobna chybka k bodu 3. Kdyz jsem u zakaznika zmenil na email a ten email nastavil, pak dal zkopirovat starou FA, ktera jeste byla POST, tak se vse probehlo jak ma, akorat v definici te nove FA zustalo POST, presto ze se spravne odeslala emailem jak mela. Cili pouze send type jeste zmenit.

**Comment by jzelenka** [comment]
Jses si tim jistej?  ted jsem to zkousel a send type se zmeni.
Navic to v kodu je.
Navic nejde fakturu poslat emailem kdyz ma sendType POST

Opravil jsem jinou chybu - kdyz das Issue & Send emailem a email spadne treba na neprirazeny eventType, tak to nehlasilo nic a issue se provedl. Ted je tam videt hlaska a issue se nedokonci.

**Comment by milant007** [comment]
Sorry ono bylo Post vyplňeno ještě v internal comment. To tam bylo aby to dokázali nějak odlišit a já si to spletl.

**Comment by milant007** [comment]
Je to na wiki: https://github.com/zauzoo/app/wiki/Fakturace_emailing
