### ISSUE TITLE
Automatické posílání FA - obrazky do html testu emailu

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#90]
Někdo bude chtít v html textu vložit i obrázek, např. logo. Vím že to řeší třebas na Heiru... Ale prioritu to má nulovou...

**Comment by jzelenka** [comment]
Obrazek se uploadne do eventTemplate resources a nastavi se mu typ Inline Image.
V html textu body se pouzije:

`<img src="cid:name"/>`

Kde to `name` je Name toho resource (obrazku). 
`cid` je tam natvrdo
 

Kdyz budes chtit dat logo profitCentera musis nastavit template pro kazde profit centrum
