### ISSUE TITLE
Automatické posílání FA - staticke prilohy

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#92]
Stálá příloha u fakturace. České Volvo nyní vyžaduje, že s každou elektronickou FA odchází ještě jedno PDFko, které je pořád stejné. 
Takže pokud by to šlo tak takovéto přílohy uploadnout přímo do Event_type v definici odesílání FA?

**Comment by jzelenka** [comment]
Hotovo, priloha se uploadne jako resource do EventTemplate, stejnym zpusobem jako u documentTemplate.
Navic se po uploadu musi nastavit typ resource: Static Attachment.
