### ISSUE TITLE
Issue FA - postřehy

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#94]
Pridavam, nejake postrehy k normalnimu ISSUE faktury na kterych netrvam, jen by to asi ulehcilo praci:
1. Pridal bych jeste jedno tlacitko. ISSUE & [PRINT or EMAIL] v zavislosti na tom zda ma ten zakaznik nastavenou emailovou fakturaci nebo ne. PRINT by rovnou otevrelo novou zalozku s nahledem pro tisk a oznacilo jiz jako odeslane postou. EMAIL by rovnou poslal email.
2. Byla by moznost uploadnout prilohu rovnou v tomto okne a v pripade volby email rovnou odeslat s tim.

**Comment by jzelenka** [comment]
myslis to tlacitko "ISSUE & PRINT or EMAIL" a moznost pridat prilohu pridat do dialogoveho okna Issue Invoice?

**Comment by milant007** [comment]
ano

**Comment by jzelenka** [comment]
Oboji hotove.

To Issue je resene jako split button - muzes kliknout na prvni cast buttonu a pak to udela defaultni akci - issue, nebo na sipecku a pak se rozbali do menu kde prvni je vzdy ta defaultni akce a nasleduji dalsi. V tomto pripade Email nebo Post (uz je vybrana jedna z nich a u emailu je uz videt emailova adresa.

Post tedy (krome toho ze to oznaci jako poslane postou) otevre okno s PDF.  Okno musi byt otevrene hned a PDF se do nej nahraje az za cca 1 - 2 sec. Duvod je ten ze kdyby se cekalo az se PDF vytvori a pak teprve se otevrelo okno, tak se ztrati tzv. safe execution context a okno muze byt zablokovano popup blockerem.
