### ISSUE TITLE
Zobrazení v gridu sekundárních kontaktních informací

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#96]
Přišel dotaz ze Slovenska, že u nějakých kontaktů si zadávají více emailů či telefonů k jedné Party a pak by je rádi viděli v gridu... Půjde a případně jak? Protože když dáme zobrazit druhý, tak si pak někdo vzpomene, že chce třetí... atd. Tak mě napadlo třebas je dát pořád do sloupce email a oddělit středníkem? Fakt nevím...

**Comment by jzelenka** [comment]
No jsou dve moznosti:
1. pridat druhy, pripadne treti
2. agregovat je do jednoho sloupce

lepsi asi agregovat, ne?  

Zadefinovane (nabizejici se v gridu) by zustalo i to stare (1. email/telefon) i by tam bylo to nove (vsechny telefony/emaily) a podle toho jestli je pridat do gridu se prida komplikace do selectu - kdyby to treba bylo pomale, tak se to necha jen v nekterych gridech apod.

**Comment by milant007** [comment]
Ano, agregovat. A idealne opravdu jeden sloupec pouze na 1. email/telefon, pokud to pomuze rychlosti. Pak je otazka zda agregovany sloupec by byl na vsechno vcetne 1. kontaktu nebo pouze od 2. dal...

**Comment by jzelenka** [comment]
agregovany bude na vsechno a ty s tim pohrajes a pripravis gridy se stavajicim sloupcem nebo novym agregovanym podle toho co kde chce a jak to brzdi nebo nebrzdi.

**Comment by milant007** [comment]
souhlas

**Comment by jzelenka** [comment]
hotovo, jsou tam dve nova pole contactEmailsAll a contactPhonesAll, kde jsou vsechny kontakty.

Ale zatimco stavajici (prvni) kontakty contactEmail, contactPhone, contactMobil jsou delane na PartyContactType  (cpa_party_contact_type):
1	email
2	phone
3	mobil

Tak tyto all jsou delane pro vsechny PartyContactType dane kategorie - PHONE a EMAIL

Takze napr. do PHONE spadne PartyContactType:
2	phone	PHONE
3	mobil	PHONE
4	internal line	PHONE
5	fax	PHONE
7	contract	PHONE

a do EMAIL:
1	email
8	invoicing email

Proste kdyz vsechno tak vsechno :)

ten 
7	contract	PHONE
by asi nemel byt PHONE, predpokladam, ze k tomu doslo z nedostatku jinych kategorii - takze jsem zavedl kategorii OTHER a mel bys updatnout tento zaznam (v cpa_party_contact_type) na kategorii OTHER.
