### ISSUE TITLE
Chyba pri zakladani v Event types nova zalozka TEMPLATES

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#97]
Zakladal jsem v templates novy u **Automatic Email Invoicing Volvo SK** a vyhazuej to chybu nize nebo viz. SLACK.

Client Error
TypeError: Can't call method on undefined at TypeError (native) at e.exports (https://www.zauzoo.com/module-a26f53d7.js:12:20569) at e.exports (https://www.zauzoo.com/module-a26f53d7.js:55:31366) at https://www.zauzoo.com/module-a26f53d7.js:55:30881 at Function.entries (https://www.zauzoo.com/module-a26f53d7.js:56:803) at https://www.zauzoo.com/module-a26f53d7.js:25:6620

**Comment by jzelenka** [comment]
opraveno
