### ISSUE TITLE
Hromadne mazani polozek v gridu

### ISSUE THREAD

**Issue by milant007** [zauzoo/app#98]
Z RO ted prisel pozadavek, ze delali castecny dobropis. Zkopirovali tedy FA o velkem mnozstvi polozek a potrebovali vetsinu promazat. Slo by udelat v gridu nejake hromadne mazani na zafiltrovane polozky? Pokud samo nemaji vazbu dal a smazat uz proste nejdou... Byl tam jeste potvrzovaci message box mazete tolik a tolik polozek, ANO / NE ?

**Comment by jzelenka** [comment]
jsou dve situace:

1. hromadne mazani v editovatelnem podseznamu (radky faktury, produkty na aute)
 - tady by zadne potvrzovani nebylo, protoze se to stejne udela az pri save (stejne jako pri jednotlivem delete), asi tady nenastane situace ze by to neslo (pro nektere zaznamy).

2. hromadne mazani na top level seznamu nebo podseznamu, ktery neni editovatelny (treba auta na zakaznikovi)
 - tady by bylo to potvrzeni, nebo radeji to udelat jako ostatni hromadne joby (faktury, emaily)

Co udelat zatim jen bod 1.  - to je to co potrebovali rumuni.

**Comment by milant007** [comment]
bod 1 staci

**Comment by jzelenka** [comment]
bod 1 hotovy, tedy jde hromadne mazat na editovatelnych podseznamech.
